{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PoiNotFound"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError\/PoiNotFound","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"IndoorSDK"}],"title":"IndoorModule.RequestAirportError.PoiNotFound","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PoiNotFound"}],"externalID":"s:9IndoorSDK0A6ModuleC19RequestAirportErrorO11PoiNotFoundyA2EmF"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Error when try to get info about the Poi, several things could happen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but most probable are the Poi is not in DB (you must check than the airport"},{"text":" ","type":"text"},{"type":"text","text":"of this pois is already downladed) or the identifier of  poi is wrong"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/requestairporterror\/poinotfound"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/RequestAirportError/PoiNotFound":{"title":"IndoorModule.RequestAirportError.PoiNotFound","abstract":[{"text":"Error when try to get info about the Poi, several things could happen","type":"text"},{"type":"text","text":" "},{"text":"but most probable are the Poi is not in DB (you must check than the airport","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of this pois is already downladed) or the identifier of  poi is wrong"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PoiNotFound"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError\/PoiNotFound","url":"\/documentation\/indoorsdk\/indoormodule\/requestairporterror\/poinotfound"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/RequestAirportError":{"navigatorTitle":[{"text":"RequestAirportError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors than could happen when try to obtain airport info from the Indoor Mobile DB."}],"role":"symbol","type":"topic","title":"IndoorModule.RequestAirportError","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestAirportError","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule\/requestairporterror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"value":[{"text":"IndoorModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","op":"replace","value":[{"text":"IndoorModule","kind":"identifier"}]}]}]}