{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiDontExist"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/openpoierror\/poidontexist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/openpoierror\/poidontexist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiDontExist","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Poi doesn’t exist in the airport. The idPoi should be wrong."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiDontExist"}],"title":"OpenPoiError.PoiDontExist","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@IndoorSDK@E@OpenPoiError@OpenPoiErrorPoiDontExist","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/PoiDontExist":{"role":"symbol","title":"OpenPoiError.PoiDontExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiDontExist"}],"abstract":[{"type":"text","text":"The Poi doesn’t exist in the airport. The idPoi should be wrong."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiDontExist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}],"url":"\/documentation\/indoorsdk\/openpoierror\/poidontexist"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError":{"role":"symbol","title":"OpenPoiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPoiError"}],"abstract":[{"type":"text","text":"Errors when you try to open a Poi, and it’s not success."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPoiError"}],"url":"\/documentation\/indoorsdk\/openpoierror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OpenPoiErrorPoiDontExist"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiDontExist\/title","value":"OpenPoiErrorPoiDontExist"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiDontExist\/fragments","value":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/title","value":"OpenPoiError"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/fragments","value":[{"kind":"identifier","text":"OpenPoiError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}