{"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut","interfaceLanguage":"swift"},"abstract":[{"text":"route checked as user origin but the user is not inside the airport","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteuserisout"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadRouteUserIsOut","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"externalID":"s:9IndoorSDK0A17MapViewControllerC15LoadOptionErrorO18loadRouteUserIsOutyA2EmF","modules":[{"name":"IndoorSDK"}],"symbolKind":"case","title":"IndoorMapViewController.LoadOptionError.loadRouteUserIsOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadRouteUserIsOut"}],"role":"symbol","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError":{"title":"IndoorMapViewController.LoadOptionError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadOptionError"}],"role":"symbol","navigatorTitle":[{"text":"LoadOptionError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Errors than could happen when you try to load an airport with some options"}],"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRouteUserIsOut":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadRouteUserIsOut"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteuserisout","kind":"symbol","title":"IndoorMapViewController.LoadOptionError.loadRouteUserIsOut","type":"topic","abstract":[{"type":"text","text":"route checked as user origin but the user is not inside the airport"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"IndoorMapViewController","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title"},{"value":[{"kind":"identifier","text":"IndoorMapViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}