{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/localizedDescription","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"Error.localizedDescription","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/Error-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"localizedDescription","modules":[{"relatedModules":["Swift"],"name":"IndoorSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:9IndoorSDK0A17MapViewControllerC15LoadOptionErrorO","platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"8.0","unavailable":false},{"introducedAt":"8.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"8.0","name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"deprecated":false,"introducedAt":"10.10","name":"macOS","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"9.0","unavailable":false},{"name":"watchOS","deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"extendedModule":"Swift"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError":{"title":"IndoorMapViewController.LoadOptionError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadOptionError"}],"role":"symbol","navigatorTitle":[{"text":"LoadOptionError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Errors than could happen when you try to load an airport with some options"}],"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/localizedDescription":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/localizedDescription","kind":"symbol","title":"localizedDescription","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/Error-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/Error-Implementations","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/error-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController","op":"replace"},{"value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace"}]}]}