{"primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Indoor SDK has added in its new release 1.4, new functionalities, and also it has expose more options to the AENA App in other to show more accuracy result to the users requests."}]},{"inlineContent":[{"text":"Now you can see on the map only the pois of a category and even only several its subcategories.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"New functions","anchor":"New-functions"},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this to enter in straigtaway in a floor of a building of  airport with a filtered category and optionaly some subcategories."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this to present a route to the user"}]},{"level":3,"text":"Helpers","type":"heading","anchor":"Helpers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to focus the map in a building and floor, it’s needed to know the identifiers of both."},{"type":"text","text":" "},{"text":"This identifiers are part of the Indoor Mobile Api, and the AENA App doesn’t know anything of these.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"IndoorSDK expose a couple of function to obtain the identifiers"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportInfo(_:completion:)"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"With this function you have a brief info about the Airport with all identifiers, names and other useful info"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestPoiPlacement(_:completion:)"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here you could have the building and floor identifiers from a POI known"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/chatbotintegration"]},{"paths":["\/documentation\/indoorsdk\/chatbotintegration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"metadata":{"title":"Chatbot integrations","modules":[{"name":"IndoorSDK"}],"role":"article","platforms":[{"introducedAt":"1.4","name":"IndoorSDK","beta":false}],"roleHeading":"Article"},"abstract":[{"type":"text","text":"Improving access to indoor maps functionalities"}],"seeAlsoSections":[{"generated":true,"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"abstract":[{"text":"Manage in your app registered region by AENA.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","type":"topic","url":"\/documentation\/indoorsdk\/geofence","kind":"article","title":"Geofence","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestPoiPlacement(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestPoiPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"), ","kind":"text"},{"kind":"typeIdentifier","text":"RequestAirportError","preciseIdentifier":"s:9IndoorSDK0A6ModuleC19RequestAirportErrorO"},{"kind":"text","text":">) -> ())"}],"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestPoiPlacement(_:completion:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/requestpoiplacement(_:completion:)","type":"topic","abstract":[{"text":"Requesting to Indoor Mobile DB the place of a  poi.","type":"text"}],"title":"requestPoiPlacement(_:completion:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"withFilterCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"], ","kind":"text"},{"text":"focusedIn","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","kind":"symbol","abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"text":" ","type":"text"},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"text":"You should also specifier witch building and floor to focus.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadRoute(inAirport:startFromUser:poisID:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","title":"loadRoute(inAirport:startFromUser:poisID:)","kind":"symbol","type":"topic","abstract":[{"text":"Load the airport in pre-route mode with a proposed route to the user","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"startFromUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"poisID","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","type":"topic","title":"Share Position","url":"\/documentation\/indoorsdk\/shareposition","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","abstract":[{"type":"text","text":"Let your users share the position"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportInfo(_:completion:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportInfo(_:completion:)","title":"requestAirportInfo(_:completion:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Requesting to Indoor Mobile DB the Info about the airport."}],"url":"\/documentation\/indoorsdk\/indoormodule\/requestairportinfo(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAirportInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK11AirportInfoV","text":"AirportInfo"},{"text":", ","kind":"text"},{"text":"RequestAirportError","kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK0A6ModuleC19RequestAirportErrorO"},{"text":">) -> ())","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"title":"Getting started","url":"\/documentation\/indoorsdk\/gettingstarted","type":"topic","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation","kind":"article","role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","title":"Outdoor navigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"title":"Essentials","anchor":"Essentials"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}]}]}]}