{"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"title":"CreateFlightError","externalID":"c:@M@IndoorSDK@E@CreateFlightError","role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/SQ","doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","doc:\/\/com.geographica.IndoorSDK\/SH","doc:\/\/com.geographica.IndoorSDK\/SY","doc:\/\/com.geographica.IndoorSDK\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There is not a required key (or the data in this key is no valid)."}]},{"inlineContent":[{"text":"Use: ","type":"text"},{"type":"codeVoice","code":"localizedDescription"},{"type":"text","text":" to know the missing key."}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/companyCode","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/numberFlight","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/state"]},{"title":"Initializers","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/localizedDescription"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/Equatable-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/createflighterror"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"title":"CreateFlightError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/nameAirportDestiny":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorNameAirportDestiny"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nameAirportDestiny","kind":"identifier"}],"title":"CreateFlightError.nameAirportDestiny","url":"\/documentation\/indoorsdk\/createflighterror\/nameairportdestiny","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportDestiny"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/icaoAirportDestiny":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorIcaoAirportDestiny"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icaoAirportDestiny"}],"url":"\/documentation\/indoorsdk\/createflighterror\/icaoairportdestiny","title":"CreateFlightError.icaoAirportDestiny","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportDestiny"},"doc://com.geographica.IndoorSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SY"},"doc://com.geographica.IndoorSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SH"},"doc://com.geographica.IndoorSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s8SendableP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/airportDestiny":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportDestiny","title":"CreateFlightError.airportDestiny","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"airportDestiny"}],"url":"\/documentation\/indoorsdk\/createflighterror\/airportdestiny","navigatorTitle":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}],"abstract":[]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/indoorsdk\/createflighterror\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/Equatable-Implementations","kind":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/indoorsdk\/createflighterror\/rawrepresentable-implementations","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/RawRepresentable-Implementations"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/nameAirportOrigin":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorNameAirportOrigin"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameAirportOrigin"}],"abstract":[],"title":"CreateFlightError.nameAirportOrigin","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportOrigin","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror\/nameairportorigin","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/companyCode":{"role":"symbol","type":"topic","title":"CreateFlightError.companyCode","url":"\/documentation\/indoorsdk\/createflighterror\/companycode","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/companyCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"companyCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorCompanyCode"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/numberFlight":{"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/numberFlight","url":"\/documentation\/indoorsdk\/createflighterror\/numberflight","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"numberFlight","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CreateFlightErrorNumberFlight","kind":"identifier"}],"title":"CreateFlightError.numberFlight","abstract":[]},"doc://com.geographica.IndoorSDK/SQ":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/s5ErrorP":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","type":"unresolvable","title":"Swift.Error"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/localizedDescription":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"title":"localizedDescription","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/localizedDescription","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror\/localizeddescription","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/state":{"role":"symbol","type":"topic","title":"CreateFlightError.state","url":"\/documentation\/indoorsdk\/createflighterror\/state","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/state","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CreateFlightErrorState","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/airportOrigin":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"airportOrigin","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/createflighterror\/airportorigin","kind":"symbol","abstract":[],"title":"CreateFlightError.airportOrigin","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportOrigin","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorAirportOrigin"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/icaoAirportOrigin":{"role":"symbol","type":"topic","title":"CreateFlightError.icaoAirportOrigin","url":"\/documentation\/indoorsdk\/createflighterror\/icaoairportorigin","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportOrigin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icaoAirportOrigin"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorIcaoAirportOrigin"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/indoorsdk\/createflighterror\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/init(rawValue:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"CreateFlightError"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"CreateFlightError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CreateFlightError"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/companyCode","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportDestiny","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportOrigin","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/numberFlight","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/state"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","value":"CreateFlightError"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","op":"replace","value":[{"text":"CreateFlightError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportDestiny\/title","value":"CreateFlightErrorNameAirportDestiny","op":"replace"},{"value":[{"kind":"identifier","text":"CreateFlightErrorNameAirportDestiny"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportDestiny\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportDestiny\/title","value":"CreateFlightErrorIcaoAirportDestiny"},{"op":"replace","value":[{"text":"CreateFlightErrorIcaoAirportDestiny","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportDestiny\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportDestiny\/title","op":"replace","value":"CreateFlightErrorAirportDestiny"},{"op":"replace","value":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportDestiny\/fragments"},{"op":"replace","value":"CreateFlightErrorNameAirportOrigin","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportOrigin\/title"},{"op":"replace","value":[{"text":"CreateFlightErrorNameAirportOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportOrigin\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1companyCode\/title","value":"CreateFlightErrorCompanyCode"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1companyCode\/fragments","value":[{"text":"CreateFlightErrorCompanyCode","kind":"identifier"}]},{"value":"CreateFlightErrorNumberFlight","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1numberFlight\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1numberFlight\/fragments","value":[{"kind":"identifier","text":"CreateFlightErrorNumberFlight"}],"op":"replace"},{"value":"CreateFlightErrorState","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1state\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CreateFlightErrorState"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1state\/fragments"},{"op":"replace","value":"CreateFlightErrorAirportOrigin","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportOrigin\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportOrigin\/fragments","value":[{"kind":"identifier","text":"CreateFlightErrorAirportOrigin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportOrigin\/title","value":"CreateFlightErrorIcaoAirportOrigin"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportOrigin\/fragments","value":[{"kind":"identifier","text":"CreateFlightErrorIcaoAirportOrigin"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}