{"seeAlsoSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true,"title":"Essentials"}],"variants":[{"paths":["\/documentation\/indoorsdk\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/gettingstarted"]}],"kind":"article","abstract":[{"text":"Add IndoorSDK to your app.","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"IndoorSDK is an indoor map, position and navigation framework.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Step 1: Add frameworks to your App","anchor":"Step-1-Add-frameworks-to-your-App","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Add the package to your project. In Xcode open ‘File’ menu and select ‘Add Packages…’ in the Swift Packages screen, search ‘aena-xcframework’ or use the url https:\/\/github.com\/CartoDB\/aena-xcframework to find, and add the package.","type":"text"}]},{"type":"heading","text":"Step 2: Requiered Keys to add at “info.plist”","level":2,"anchor":"Step-2-Requiered-Keys-to-add-at-infoplist"},{"type":"paragraph","inlineContent":[{"text":"In the info.plist of your project you must add the following keys and its proper value.","type":"text"}]},{"inlineContent":[{"inlineContent":[{"text":"Privacy - Location When In Use Usage Description","type":"text"}],"type":"strong"}],"type":"paragraph"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Privacy - Bluetooth Always Usage Description"}]}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In both add a message that tells the user than the app is requesting access to the user’s location information while the app is running."}]},{"text":"Step 3: Background Modes","level":2,"type":"heading","anchor":"Step-3-Background-Modes"},{"inlineContent":[{"type":"text","text":"In "},{"inlineContent":[{"type":"text","text":"Signing & Capabilities"}],"type":"emphasis"},{"text":" of your project settings, add ","type":"text"},{"inlineContent":[{"type":"text","text":"Background Modes"}],"type":"strong"},{"type":"text","text":" and select the modes according to the next image."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"backModes.png"}]},{"type":"heading","text":"Step 4: Start the framework","anchor":"Step-4-Start-the-framework","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the method "},{"inlineContent":[{"type":"text","text":"didFinishLaunchingWithOptions"}],"type":"emphasis"},{"type":"text","text":" of your "},{"inlineContent":[{"type":"text","text":"AppDelegate"}],"type":"emphasis"},{"text":" you should start the IndoorSDK:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","  ","    IndoorModule.shared.start()","","   \/\/ Override point for customization after application launch.","    return true","}",""]},{"inlineContent":[{"type":"text","text":"Several functionalities of the framework depends of its early start."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The first time you start the framework the prompt requesting location authorization will be launch."}]}],"name":"Note","type":"aside","style":"note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to delay the authorization request add "},{"type":"emphasis","inlineContent":[{"type":"text","text":"false"}]},{"text":" to the ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"start","type":"text"}]},{"text":" parameter.","type":"text"}]},{"type":"codeListing","code":["IndoorModule.shared.start(false) "],"syntax":"swift"},{"anchor":"Step-5-Add-View-Controller","type":"heading","text":"Step 5: Add View Controller","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"To show the map create an "},{"type":"reference","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","isActive":true},{"type":"text","text":", load the airport "},{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","type":"reference","isActive":true},{"text":" and push inside a navigation controller","type":"text"}]},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"IndoorMapViewController must always be inside a navigation controller."}]}]},{"type":"codeListing","syntax":"swift","code":["let vC = IndoorMapViewController()","         vC.loadAirport(icao: \"LEMD\")","        navigationController?.pushViewController(vC, animated: true)",""]},{"name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"Don’t forget load the airport.","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"sections":[],"metadata":{"modules":[{"name":"IndoorSDK"}],"roleHeading":"Article","role":"article","title":"Getting started"},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","interfaceLanguage":"swift"},"references":{"backModes.png":{"alt":"Add XcFrame and to section.","variants":[{"traits":["1x","light"],"url":"\/images\/com.geographica.IndoorSDK\/backModes.png"}],"type":"image","identifier":"backModes.png"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","type":"topic","title":"Share Position","url":"\/documentation\/indoorsdk\/shareposition","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","abstract":[{"type":"text","text":"Let your users share the position"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation","kind":"article","role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","title":"Outdoor navigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/ChatbotIntegration":{"role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","type":"topic","kind":"article","url":"\/documentation\/indoorsdk\/chatbotintegration","title":"Chatbot integrations","abstract":[{"type":"text","text":"Improving access to indoor maps functionalities"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"icao","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Load the airport.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)","role":"symbol","title":"loadAirport(icao:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"abstract":[{"text":"Manage in your app registered region by AENA.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","type":"topic","url":"\/documentation\/indoorsdk\/geofence","kind":"article","title":"Geofence","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"title":"Essentials","generated":true,"anchor":"Essentials"}],"op":"replace"},{"value":"IndoorModule","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title"},{"value":[{"text":"IndoorModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorModule"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title","op":"replace","value":"loadAirportWithIcao:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAirportWithIcao:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","value":[{"text":"IndoorMapViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"},{"value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}