{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyisindoor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyisindoor"]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyIsIndoor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@IndoorSDKPositionKeyIsIndoor","roleHeading":"Global Variable","role":"symbol","title":"IndoorSDKPositionKeyIsIndoor","modules":[{"name":"IndoorSDK"}],"symbolKind":"var","navigatorTitle":[{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Is indoor key. Bool. true = indoor \/ false = outdoor.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyIsIndoor":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"IndoorSDKPositionKeyIsIndoor","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyIsIndoor","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyisindoor","abstract":[{"text":"Is indoor key. Bool. true = indoor \/ false = outdoor.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyIsIndoor"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"IndoorSDKPositionKeyIsIndoor"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyIsIndoor\/title","value":"IndoorSDKPositionKeyIsIndoor"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyIsIndoor\/fragments","value":[{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}