{"abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"seeAlsoSections":[{"title":"Essentials","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"anchor":"Essentials"}],"topicSections":[{"anchor":"Main","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"],"title":"Main"},{"title":"Utils","anchor":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"]},{"anchor":"Share-Location","title":"Share Location","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageUserActivity(_:andPresentIn:after:prepareToPresent:)"]},{"title":"Outdoor Navigation","anchor":"Outdoor-Navigation","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)"]},{"title":"Geofence","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/userActiveNotifications(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/GeofenceNew","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/enterInGeofenceAction"],"anchor":"Geofence"},{"anchor":"Info","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/build","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/version"],"title":"Info"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"title":"Deprecated","anchor":"Deprecated"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/isIndoorResponse(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportInfo(_:completion:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestPoiPlacement(_:completion:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/SearchSelectCategoryNotification","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/SearchSelectPoiNotification"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError"],"title":"Enumerations","anchor":"Enumerations","generated":true}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSObject","doc:\/\/com.geographica.IndoorSDK\/s7CVarArgP","doc:\/\/com.geographica.IndoorSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.geographica.IndoorSDK\/s23CustomStringConvertibleP","doc:\/\/com.geographica.IndoorSDK\/SQ","doc:\/\/com.geographica.IndoorSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It’s a singlenton, you must call ‘shared’."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}],"externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule","symbolKind":"class","title":"IndoorModule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorModule"}],"role":"symbol","modules":[{"name":"IndoorSDK"}],"roleHeading":"Class"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/enterInGeofenceAction":{"abstract":[{"text":"Function to manage Geofence functionality","type":"text"}],"title":"enterInGeofenceAction","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/enterInGeofenceAction","url":"\/documentation\/indoorsdk\/indoormodule\/enteringeofenceaction","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enterInGeofenceAction","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"GeofenceNew","preciseIdentifier":"s:9IndoorSDK0A6ModuleC11GeofenceNewV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")?","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportsInfoFromIcaos(_:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)","navigatorTitle":[{"text":"requestAirportsInfoFromIcaos:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"requestAirportsInfoFromIcaos(_:)","url":"\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestAirportsInfoFromIcaos","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"abstract":[{"text":"Request all info about airports","type":"text"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlightInfo(_:)":{"type":"topic","abstract":[{"type":"text","text":"Set the info about the flight."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","role":"symbol","title":"setFlightInfo(_:)","kind":"symbol","navigatorTitle":[{"text":"setFlightInfo:","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlightInfo"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"deprecated":true},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/SearchSelectPoiNotification":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/SearchSelectPoiNotification","url":"\/documentation\/indoorsdk\/indoormodule\/searchselectpoinotification","title":"SearchSelectPoiNotification","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchSelectPoiNotification","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name","kind":"typeIdentifier"}],"type":"topic"},"doc://com.geographica.IndoorSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SH"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"abstract":[{"text":"Manage in your app registered region by AENA.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","type":"topic","url":"\/documentation\/indoorsdk\/geofence","kind":"article","title":"Geofence","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/isIndoorResponse(_:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/isIndoorResponse(_:)","url":"\/documentation\/indoorsdk\/indoormodule\/isindoorresponse(_:)","kind":"symbol","abstract":[{"type":"text","text":"To ask if a new notification is managed by the indoor module"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isIndoorResponse"},{"text":"(","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","type":"topic","title":"isIndoorResponse(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/userActiveNotifications(_:)":{"role":"symbol","title":"userActiveNotifications(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userActiveNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK0A6ModuleC20UserNotificationKindV","text":"UserNotificationKind"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/useractivenotifications(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/userActiveNotifications(_:)","abstract":[{"text":"Use this to set the user notifications selection.","type":"text"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadCategory(_:inAirport:inNavController:action:)":{"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)","navigatorTitle":[{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","title":"loadCategory(_:inAirport:inNavController:action:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCategory"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"text":": (([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/shared":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"IndoorModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/indoorsdk\/indoormodule\/shared","role":"symbol","title":"shared","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","abstract":[{"text":"The shared instance of IndoorSDK class.","type":"text"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportInfo(_:completion:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportInfo(_:completion:)","title":"requestAirportInfo(_:completion:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Requesting to Indoor Mobile DB the Info about the airport."}],"url":"\/documentation\/indoorsdk\/indoormodule\/requestairportinfo(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAirportInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK11AirportInfoV","text":"AirportInfo"},{"text":", ","kind":"text"},{"text":"RequestAirportError","kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK0A6ModuleC19RequestAirportErrorO"},{"text":">) -> ())","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/start(_:)":{"url":"\/documentation\/indoorsdk\/indoormodule\/start(_:)","kind":"symbol","title":"start(_:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"start:","kind":"identifier"}],"abstract":[{"text":"It start all stuff","type":"text"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setPMR(_:)":{"type":"topic","abstract":[{"type":"text","text":"Switch On\/Off the "},{"type":"strong","inlineContent":[{"text":"PRM","type":"text"}]},{"type":"text","text":" routes"},{"type":"text","text":" "},{"type":"text","text":"(People Reduced Mobility)"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","role":"symbol","title":"setPMR(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPMR:"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/ChatbotIntegration":{"role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","type":"topic","kind":"article","url":"\/documentation\/indoorsdk\/chatbotintegration","title":"Chatbot integrations","abstract":[{"type":"text","text":"Improving access to indoor maps functionalities"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/manageUserActivity(_:andPresentIn:after:prepareToPresent:)":{"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageUserActivity(_:andPresentIn:after:prepareToPresent:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"manageUserActivity","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUserActivity","text":"NSUserActivity","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andPresentIn","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"after"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"prepareToPresent"},{"text":": () -> ()) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/indoorsdk\/indoormodule\/manageuseractivity(_:andpresentin:after:preparetopresent:)","title":"manageUserActivity(_:andPresentIn:after:prepareToPresent:)","abstract":[{"type":"text","text":"}"}]},"doc://com.geographica.IndoorSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SQ"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/UserNotificationKind":{"abstract":[{"type":"text","text":"In AENA App users could chose receive info inside three different category, operational, commercial and third parties. This element represent these categories in order of the App info to IndoorSDK about user selection."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"UserNotificationKind","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/usernotificationkind","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind","navigatorTitle":[{"kind":"identifier","text":"UserNotificationKind"}],"title":"IndoorModule.UserNotificationKind","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"manageNotificationResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andPresentIn"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"after","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"], ","kind":"text"},{"text":"prepareToPresent","kind":"externalParam"},{"kind":"text","text":": () -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/managenotificationresponse(_:andpresentin:after:preparetopresent:)","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)","type":"topic","abstract":[{"text":"if IndoorModule.shared.manageNotificationResponse(response, andPresentIn: navController, after: [MainDemoAppTViewController(style: .plain)], prepareToPresent: { self.tabBar.selectedIndex = 1 })","type":"text"},{"type":"text","text":" "},{"type":"text","text":"{"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Managed by Indoor module."},{"type":"text","text":" "},{"type":"text","text":"return"},{"type":"text","text":" "},{"text":"}","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/build":{"abstract":[{"text":"Info about the current build","type":"text"}],"title":"build","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/build","url":"\/documentation\/indoorsdk\/indoormodule\/build","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/GeofenceNew":{"title":"IndoorModule.GeofenceNew","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/GeofenceNew","abstract":[{"type":"text","text":"News related with a region in airport."}],"navigatorTitle":[{"kind":"identifier","text":"GeofenceNew"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeofenceNew"}],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/geofencenew","kind":"symbol"},"doc://com.geographica.IndoorSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.geographica.IndoorSDK\/s7CVarArgP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/RequestAirportError":{"navigatorTitle":[{"text":"RequestAirportError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors than could happen when try to obtain airport info from the Indoor Mobile DB."}],"role":"symbol","type":"topic","title":"IndoorModule.RequestAirportError","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/RequestAirportError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestAirportError","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule\/requestairporterror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestPoiPlacement(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestPoiPlacement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"), ","kind":"text"},{"kind":"typeIdentifier","text":"RequestAirportError","preciseIdentifier":"s:9IndoorSDK0A6ModuleC19RequestAirportErrorO"},{"kind":"text","text":">) -> ())"}],"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestPoiPlacement(_:completion:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/requestpoiplacement(_:completion:)","type":"topic","abstract":[{"text":"Requesting to Indoor Mobile DB the place of a  poi.","type":"text"}],"title":"requestPoiPlacement(_:completion:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/airportIsCached(_:)":{"url":"\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)","navigatorTitle":[{"kind":"identifier","text":"airportIsCached:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"To ask if an airport is ready"}],"title":"airportIsCached(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)"},"doc://com.geographica.IndoorSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(cs)NSObject"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation","kind":"article","role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","title":"Outdoor navigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getPosition()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPosition"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"title":"getPosition()","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"User last position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getposition()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","type":"topic","title":"Share Position","url":"\/documentation\/indoorsdk\/shareposition","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","abstract":[{"type":"text","text":"Let your users share the position"}]},"doc://com.geographica.IndoorSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSObject"},"doc://com.geographica.IndoorSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.geographica.IndoorSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.geographica.IndoorSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.geographica.IndoorSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/SearchSelectCategoryNotification":{"abstract":[],"title":"SearchSelectCategoryNotification","role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/searchselectcategorynotification","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchSelectCategoryNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/SearchSelectCategoryNotification"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"title":"Getting started","url":"\/documentation\/indoorsdk\/gettingstarted","type":"topic","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/action":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"title":"action","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Action to be excecute when the "},{"type":"codeVoice","code":"flight info"},{"text":" ","type":"text"},{"type":"text","text":"button is pressed."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","url":"\/documentation\/indoorsdk\/indoormodule\/action"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey","kind":"symbol","title":"IndoorModule.PositionKey","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositionKey"}],"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"abstract":[{"text":"Define the constanst keys of the position dictionary.","type":"text"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadSaveParking(inAirport:inNavController:action:)":{"title":"loadSaveParking(inAirport:inNavController:action:)","role":"symbol","abstract":[{"type":"text","text":"Open the save carpark screen inside the provide navigation controller."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)","url":"\/documentation\/indoorsdk\/indoormodule\/loadsaveparking(inairport:innavcontroller:action:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadSaveParking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getUserPosition()":{"type":"topic","navigatorTitle":[{"text":"getUserPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"User last position"}],"kind":"symbol","title":"getUserPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getuserposition()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserPosition"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlight(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlight"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflight(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","title":"setFlight(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFlight:error:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/version":{"role":"symbol","title":"version","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/version","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/version","type":"topic","abstract":[{"text":"Info about the current version","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"IndoorModule"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace"},{"value":[{"title":"Main","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"],"anchor":"Main"},{"title":"Utils","anchor":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"]},{"title":"Deprecated","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"anchor":"Deprecated"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"title":"Essentials","anchor":"Essentials","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/title","op":"replace","value":"requestAirportsInfoFromIcaos:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestAirportsInfoFromIcaos:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/title","value":"setFlightInfo:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setFlightInfo:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"text":"IndoorMapViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/title","value":"loadCategory:inAirport:inNavController:error:action:"},{"value":[{"text":"- ","kind":"text"},{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/title","value":"start:","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"start:"}]},{"op":"replace","value":"setPMR:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPMR:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","op":"replace","value":[{"text":"IndoorModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","value":"airportIsCached:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"airportIsCached:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/title","op":"replace","value":"getPosition"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getPosition"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/title","value":"action","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/fragments","op":"replace","value":[{"text":"action","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/title","value":"loadSaveParkingInAirport:inNavController:error:action:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/title","value":"getUserPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getUserPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/title","value":"setFlight:error:"},{"value":[{"kind":"text","text":"- "},{"text":"setFlight:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}