{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyFloorId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"abstract":[{"text":"Floor identifier key. String. -1 means outdoor, ground floor.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyfloorid"]},{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyfloorid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyFloorId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Global Variable","title":"IndoorSDKPositionKeyFloorId","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"}],"externalID":"c:@IndoorSDKPositionKeyFloorId","symbolKind":"var"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyFloorId":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyFloorId","abstract":[{"type":"text","text":"Floor identifier key. String. -1 means outdoor, ground floor."}],"kind":"symbol","title":"IndoorSDKPositionKeyFloorId","role":"symbol","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyfloorid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"IndoorSDKPositionKeyFloorId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"IndoorSDKPositionKeyFloorId","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyFloorId\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyFloorId\/fragments","value":[{"text":"IndoorSDKPositionKeyFloorId","kind":"identifier"}],"op":"replace"}]}]}