{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLatitude"},"metadata":{"role":"symbol","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyLatitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"}],"title":"IndoorSDKPositionKeyLatitude","externalID":"c:@IndoorSDKPositionKeyLatitude","modules":[{"name":"IndoorSDK"}],"roleHeading":"Global Variable"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Latitude key. Double. The longitude of the position."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeylatitude"]},{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeylatitude"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyLatitude":{"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeylatitude","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyLatitude"}],"kind":"symbol","title":"IndoorSDKPositionKeyLatitude","abstract":[{"text":"Latitude key. Double. The longitude of the position.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLatitude","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","value":"IndoorSDKPositionKeyLatitude","op":"replace"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyLatitude"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"IndoorSDKPositionKeyLatitude","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLatitude\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLatitude\/fragments","op":"replace","value":[{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"}]}]}]}