{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(cs)UIViewController"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSCoding","doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSObject","doc:\/\/com.geographica.IndoorSDK\/s7CVarArgP","doc:\/\/com.geographica.IndoorSDK\/s8CopyableP","doc:\/\/com.geographica.IndoorSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.geographica.IndoorSDK\/s23CustomStringConvertibleP","doc:\/\/com.geographica.IndoorSDK\/SQ","doc:\/\/com.geographica.IndoorSDK\/SH","doc:\/\/com.geographica.IndoorSDK\/s8SendableP","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDataSource","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDelegate","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIContentContainer","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIScrollViewDelegate","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIStateRestoring","doc:\/\/com.geographica.IndoorSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"],"generated":true,"anchor":"Essentials"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorMapViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"You usually create and object, load and airport"},{"type":"text","text":" "},{"type":"text","text":"and push inside a navigationController."}],"type":"paragraph"},{"code":["   let vC = IndoorMapViewController()","   vC.loadAirport(icao: \"LEMD\")","   navigationController?.pushViewController(vC, animated: true)"],"type":"codeListing","syntax":null},{"level":2,"type":"heading","anchor":"Important","text":"Important"},{"type":"paragraph","inlineContent":[{"text":"All IndoorMapViewController objects must be inside","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a UINavigationController."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"symbolKind":"class","title":"IndoorMapViewController","modules":[{"name":"IndoorSDK"}],"role":"symbol","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"externalID":"c:@M@IndoorSDK@objc(cs)IndoorMapViewController","roleHeading":"Class"},"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"topicSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"],"anchor":"Override-Methods","title":"Override Methods","abstract":[{"text":"Public due to override the UIKit superclass methods, you never call.","type":"text"}]},{"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError"],"generated":true},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDelegate-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"references":{"doc://com.geographica.IndoorSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIFocusEnvironment"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/UICollectionViewDelegate-Implementations":{"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdelegate-implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDelegate-Implementations","title":"UICollectionViewDelegate Implementations"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation","kind":"article","role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","title":"Outdoor navigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/ChatbotIntegration":{"role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","type":"topic","kind":"article","url":"\/documentation\/indoorsdk\/chatbotintegration","title":"Chatbot integrations","abstract":[{"type":"text","text":"Improving access to indoor maps functionalities"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"navigatorTitle":[{"text":"openPoiWithIdPoi:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","abstract":[{"text":"Open a POI in a loaded Airpot.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)","role":"symbol","title":"openPoi(idPoi:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillDisappear(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","title":"viewWillDisappear(_:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwilldisappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/5UIKit23UITraitChangeObservableP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"title":"Getting started","url":"\/documentation\/indoorsdk\/gettingstarted","type":"topic","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","role":"article"},"doc://com.geographica.IndoorSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIAppearanceContainer"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"icao","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Load the airport.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)","role":"symbol","title":"loadAirport(icao:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/accessibilityPerformEscape()":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/accessibilityperformescape()","title":"accessibilityPerformEscape()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformEscape"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformEscape"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()"},"doc://com.geographica.IndoorSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s7CVarArgP"},"doc://com.geographica.IndoorSDK/objc(pl)UICollectionViewDataSource":{"title":"UICollectionViewDataSource","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDataSource"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadPoi","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"err","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"kind":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)","abstract":[{"text":"Load the airport with the Poi selected.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/didMove(toParent:)":{"title":"didMove(toParent:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toParent"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/didmove(toparent:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"didMoveToParentViewController:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","role":"symbol"},"doc://com.geographica.IndoorSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s8SendableP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations","title":"UICollectionViewDataSource Implementations","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdatasource-implementations","abstract":[]},"doc://com.geographica.IndoorSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSObject"},"doc://com.geographica.IndoorSDK/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s8CopyableP"},"doc://com.geographica.IndoorSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIContentContainer"},"doc://com.geographica.IndoorSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.geographica.IndoorSDK/objc(pl)UIScrollViewDelegate":{"title":"UIKit.UIScrollViewDelegate","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIScrollViewDelegate"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","type":"topic","title":"Share Position","url":"\/documentation\/indoorsdk\/shareposition","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","abstract":[{"type":"text","text":"Let your users share the position"}]},"doc://com.geographica.IndoorSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)NSCoding"},"doc://com.geographica.IndoorSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s23CustomStringConvertibleP"},"doc://com.geographica.IndoorSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.geographica.IndoorSDK/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(cs)UIViewController"},"doc://com.geographica.IndoorSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s28CustomDebugStringConvertibleP"},"doc://com.geographica.IndoorSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SH"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:cellForItemAt:)":{"title":"collectionView(_:cellForItemAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"cellForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","role":"symbol"},"doc://com.geographica.IndoorSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadView()":{"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadView","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"title":"loadView()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadView"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadCarPark(_:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadcarpark(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadCarPark"},{"kind":"text","text":"("},{"preciseIdentifier":"s:9IndoorSDK7CarparkV","kind":"typeIdentifier","text":"Carpark"},{"kind":"text","text":")"}],"kind":"symbol","title":"loadCarPark(_:)","abstract":[{"text":"Load the airport with the carpark saved selected.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:didSelectItemAt:)":{"title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:didselectitemat:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)","role":"symbol"},"doc://com.geographica.IndoorSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadRoute(inAirport:startFromUser:poisID:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","title":"loadRoute(inAirport:startFromUser:poisID:)","kind":"symbol","type":"topic","abstract":[{"text":"Load the airport in pre-route mode with a proposed route to the user","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"startFromUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"poisID","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.geographica.IndoorSDK/objc(pl)UICollectionViewDelegate":{"title":"UICollectionViewDelegate","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDelegate"},"doc://com.geographica.IndoorSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SQ"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"withFilterCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"], ","kind":"text"},{"text":"focusedIn","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","kind":"symbol","abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"text":" ","type":"text"},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"text":"You should also specifier witch building and floor to focus.","type":"text"}]},"doc://com.geographica.IndoorSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UIStateRestoring"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"abstract":[{"text":"Manage in your app registered region by AENA.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","type":"topic","url":"\/documentation\/indoorsdk\/geofence","kind":"article","title":"Geofence","role":"article"},"doc://com.geographica.IndoorSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/objc(pl)UITraitEnvironment"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError":{"title":"IndoorMapViewController.LoadOptionError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadOptionError"}],"role":"symbol","navigatorTitle":[{"text":"LoadOptionError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Errors than could happen when you try to load an airport with some options"}],"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/traitCollectionDidChange(_:)":{"title":"traitCollectionDidChange(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/traitcollectiondidchange(_:)","abstract":[],"navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidLoad()":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidload()","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"IndoorMapViewController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorMapViewController"}]},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"]},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"],"anchor":"Override-Methods","title":"Override Methods","abstract":[{"type":"text","text":"Public due to override the UIKit superclass methods, you never call."}]},{"generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDelegate-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(cs)UIViewController"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDataSource","doc:\/\/com.geographica.IndoorSDK\/objc(pl)UICollectionViewDelegate"],"title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"],"title":"Essentials","anchor":"Essentials","generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","op":"replace","value":"openPoiWithIdPoi:error:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"openPoiWithIdPoi:error:","kind":"identifier"}]},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/fragments"},{"value":"loadAirportWithIcao:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAirportWithIcao:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/title","value":"accessibilityPerformEscape"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityPerformEscape","kind":"identifier"}],"op":"replace"},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},{"value":"loadPoiWithIdPoi:inAirport:readyBlock:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/title","value":"didMoveToParentViewController:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didMoveToParentViewController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/fragments"},{"value":"IndoorModule","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"text":"IndoorModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController","op":"replace"},{"value":[{"kind":"identifier","text":"IndoorMapViewController"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorMapViewController"}]},{"op":"replace","value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/title","op":"replace","value":"loadView"},{"value":[{"text":"- ","kind":"text"},{"text":"loadView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/title","op":"replace","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/title","op":"replace","value":"traitCollectionDidChange:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}