{"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLongitude","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Longitude key. Double. The latitude of the position."}],"metadata":{"modules":[{"name":"IndoorSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"}],"title":"IndoorSDKPositionKeyLongitude","symbolKind":"var","roleHeading":"Global Variable","role":"symbol","externalID":"c:@IndoorSDKPositionKeyLongitude"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeylongitude"]},{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeylongitude"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyLongitude":{"navigatorTitle":[{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Longitude key. Double. The latitude of the position."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeylongitude","title":"IndoorSDKPositionKeyLongitude","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLongitude","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"IndoorSDKPositionKeyLongitude"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"IndoorSDKPositionKeyLongitude","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLongitude\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLongitude\/fragments","value":[{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"}]}]}]}