{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPoiError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/openpoierror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/openpoierror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/SQ","doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","doc:\/\/com.geographica.IndoorSDK\/SH","doc:\/\/com.geographica.IndoorSDK\/SY","doc:\/\/com.geographica.IndoorSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Errors when you try to open a Poi, and it’s not success."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPoiError"}],"title":"OpenPoiError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@IndoorSDK@E@OpenPoiError","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"OpenPoiError"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiCantBeReach","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiDontExist"]},{"title":"Initializers","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/Equatable-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/Error-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/openpoierror\/error-implementations"},"doc://com.geographica.IndoorSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SQ"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/openpoierror\/rawrepresentable-implementations"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/PoiCantBeReach":{"role":"symbol","title":"OpenPoiError.PoiCantBeReach","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiCantBeReach"}],"abstract":[{"type":"text","text":"The poi can’t be reach, usually is a network problem."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiCantBeReach","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPoiErrorPoiCantBeReach"}],"url":"\/documentation\/indoorsdk\/openpoierror\/poicantbereach"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/openpoierror\/equatable-implementations"},"doc://com.geographica.IndoorSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SY"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/openpoierror\/init(rawvalue:)"},"doc://com.geographica.IndoorSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SH"},"doc://com.geographica.IndoorSDK/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.geographica.IndoorSDK\/s5ErrorP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/PoiDontExist":{"role":"symbol","title":"OpenPoiError.PoiDontExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiDontExist"}],"abstract":[{"type":"text","text":"The Poi doesn’t exist in the airport. The idPoi should be wrong."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiDontExist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}],"url":"\/documentation\/indoorsdk\/openpoierror\/poidontexist"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError":{"role":"symbol","title":"OpenPoiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPoiError"}],"abstract":[{"type":"text","text":"Errors when you try to open a Poi, and it’s not success."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenPoiError"}],"url":"\/documentation\/indoorsdk\/openpoierror"},"doc://com.geographica.IndoorSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OpenPoiError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OpenPoiError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OpenPoiError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiCantBeReach","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiDontExist"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenPoiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiCantBeReach\/title","value":"OpenPoiErrorPoiCantBeReach"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiCantBeReach\/fragments","value":[{"kind":"identifier","text":"OpenPoiErrorPoiCantBeReach"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiDontExist\/title","value":"OpenPoiErrorPoiDontExist"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiDontExist\/fragments","value":[{"kind":"identifier","text":"OpenPoiErrorPoiDontExist"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/title","value":"OpenPoiError"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/fragments","value":[{"kind":"identifier","text":"OpenPoiError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}