{"kind":"symbol","variants":[{"paths":["\/documentation\/indoorsdk\/opencategorylisterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/opencategorylisterror"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenCategoryListError","kind":"identifier"}],"role":"symbol","externalID":"c:@M@IndoorSDK@E@OpenCategoryListError","roleHeading":"Enumeration","title":"OpenCategoryListError","symbolKind":"enum","modules":[{"name":"IndoorSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.geographica.IndoorSDK\/SQ","doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","doc:\/\/com.geographica.IndoorSDK\/SH","doc:\/\/com.geographica.IndoorSDK\/SY","doc:\/\/com.geographica.IndoorSDK\/s8SendableP"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/AirportIsNotReady","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/CategoryDoNotExist"]},{"title":"Initializers","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/localizedDescription"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/Equatable-Implementations","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenCategoryListError"}]}]}],"references":{"doc://com.geographica.IndoorSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SQ"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/indoorsdk\/opencategorylisterror\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/RawRepresentable-Implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.geographica.IndoorSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.geographica.IndoorSDK\/SH"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/CategoryDoNotExist":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/CategoryDoNotExist","abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror\/categorydonotexist","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryDoNotExist"}],"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListErrorCategoryDoNotExist"}],"title":"OpenCategoryListError.CategoryDoNotExist"},"doc://com.geographica.IndoorSDK/s5ErrorP":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/init(rawValue:)":{"url":"\/documentation\/indoorsdk\/opencategorylisterror\/init(rawvalue:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/init(rawValue:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/AirportIsNotReady":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/AirportIsNotReady","abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror\/airportisnotready","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirportIsNotReady"}],"navigatorTitle":[{"text":"OpenCategoryListErrorAirportIsNotReady","kind":"identifier"}],"title":"OpenCategoryListError.AirportIsNotReady"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/localizedDescription":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/localizedDescription","abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror\/localizeddescription","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"localizedDescription"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror","abstract":[],"title":"OpenCategoryListError","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenCategoryListError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}]},"doc://com.geographica.IndoorSDK/s8SendableP":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.geographica.IndoorSDK/SY":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/Equatable-Implementations":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/Equatable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/indoorsdk\/opencategorylisterror\/equatable-implementations","kind":"article","type":"topic","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OpenCategoryListError"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"OpenCategoryListError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OpenCategoryListError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/AirportIsNotReady","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/CategoryDoNotExist"]}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenCategoryListError"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1CategoryDoNotExist\/title","op":"replace","value":"OpenCategoryListErrorCategoryDoNotExist"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1CategoryDoNotExist\/fragments","value":[{"text":"OpenCategoryListErrorCategoryDoNotExist","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1AirportIsNotReady\/title","value":"OpenCategoryListErrorAirportIsNotReady"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1AirportIsNotReady\/fragments","op":"replace","value":[{"text":"OpenCategoryListErrorAirportIsNotReady","kind":"identifier"}]},{"value":"OpenCategoryListError","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/fragments","value":[{"kind":"identifier","text":"OpenCategoryListError"}],"op":"replace"}]}]}