{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This functionality let users start an outdoor navigation from your app, and it manage the come back to your app with the user arrive to the airport."}]},{"anchor":"Make-outdoor-navigation-work:","level":2,"type":"heading","text":"Make outdoor navigation work:"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To manage the come back to App, Indoor SDK register several regions alerts, when the user enter of one of them, Indoor SDK evaluate the position and launch a notification."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To evaluate region and manage the return through the notification, it’s needed a two step configuration."}]},{"anchor":"Step-1:-Be-sure-the-location-services-are-on","level":4,"type":"heading","text":"Step 1: Be sure the location services are on"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To guarantee this you must start IndoorSDK as soon as possible. Be sure you make this in the appropriate method of your appDelegate"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        ","                IndoorModule.shared.start()","               \/\/ Override point for customization after application launch.","               return true","               }"]},{"anchor":"Step-2:-Manage-notification","level":4,"type":"heading","text":"Step 2: Manage notification"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When user press the notification to continue with indoor navigation, the app must open in the map to continue with route."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"IndoorSDK provide in its class "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},{"type":"text","text":" a method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)"},{"type":"text","text":" to manage this."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should implement like this in proper method of your appDelegate:"}]},{"type":"codeListing","syntax":"swift","code":["func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {","        ","        if IndoorModule.shared.manageNotificationResponse(response, andPresentIn: navController, after: [MainDemoAppTViewController(style: .plain)], prepareToPresent: { self.tabBar.selectedIndex = 1 })","        {","            \/\/ Managed by Indoor module.","            return","        }","            \/\/ Here your notifications implementation.","    }",""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/outdoornavigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/outdoornavigation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Outdoor navigation","role":"article","modules":[{"name":"IndoorSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","title":"IndoorMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorMapViewController"}],"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","title":"IndoorModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorModule"}],"abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}],"url":"\/documentation\/indoorsdk\/indoormodule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/gettingstarted"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)":{"role":"symbol","title":"manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manageNotificationResponse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andPresentIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"prepareToPresent"},{"kind":"text","text":": () -> ()) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"if IndoorModule.shared.manageNotificationResponse(response, andPresentIn: navController, after: [MainDemoAppTViewController(style: .plain)], prepareToPresent: { self.tabBar.selectedIndex = 1 })"},{"type":"text","text":" "},{"type":"text","text":"{"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Managed by Indoor module."},{"type":"text","text":" "},{"type":"text","text":"return"},{"type":"text","text":" "},{"type":"text","text":"}"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageNotificationResponse(_:andPresentIn:after:prepareToPresent:)","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormodule\/managenotificationresponse(_:andpresentin:after:preparetopresent:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","title":"Share Position","abstract":[{"type":"text","text":"Let your users share the position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/shareposition"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"role":"article","title":"Geofence","abstract":[{"type":"text","text":"Manage in your app registered region by AENA."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/geofence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}