{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This functionality let users share position in side an airport, and also to receive a share position in the App, open it in the proper map and even to navigate to it."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to configure your app to manage this functionality. Your app must support universal link, here complete info.(https:\/\/developer.apple.com\/documentation\/xcode\/supporting-universal-links-in-your-app)"}]},{"anchor":"Universal-Link-in-a-nutshell","level":2,"type":"heading","text":"Universal Link in a nutshell"},{"anchor":"Step-1:-Associated-Domains","level":5,"type":"heading","text":"Step 1: Associated Domains"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must define your url, e.g. "},{"type":"codeVoice","code":"https:\/\/aena.demo.carto.solutions"},{"type":"text","text":". Then in "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Signing & Capabilities"}]},{"type":"text","text":" of your project settings, add "},{"type":"strong","inlineContent":[{"type":"text","text":"Associated Domains"}]},{"type":"text","text":" and add the domains."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"assDomains.png"}]},{"anchor":"Step-2:-Association-file","level":5,"type":"heading","text":"Step 2: Association file"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the Associated Domain File to Your Website, create a file named "},{"type":"strong","inlineContent":[{"type":"text","text":"apple-app-site-association"}]},{"type":"text","text":" (without an extension). Update the JSON code in the file for the services you’ll support on the domain."}]},{"type":"codeListing","syntax":"swift","code":["{","      \"applinks\": {","          “details\":","             [{","                 \"appIDs\": [ \"1482639094.com.carto.aenaindoor.staging\"],","                 \"paths\": [\"\/\", \"\/position\/*\"]   ","                 }]","       }","}",""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must upload your file in your HTTPS web server, in the root or "},{"type":"strong","inlineContent":[{"type":"text","text":".well-know"}]},{"type":"text","text":" directory."}]},{"anchor":"Step-3:-Manage-in-the-App","level":5,"type":"heading","text":"Step 3: Manage in the App"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When user press the universal link to open the share position, the app must open in the map with the share position."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"IndoorSDK provide in its class "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},{"type":"text","text":" a method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageUserActivity(_:andPresentIn:after:prepareToPresent:)"},{"type":"text","text":" to manage this."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should implement like this in proper method of your appDelegate:"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {","       ","       if IndoorModule.shared.manageUserActivity(userActivity, andPresentIn: navController, after: [MainDemoAppTViewController(style: .plain)], prepareToPresent: { self.tabBar.selectedIndex = 1 })","       {","           return true","       }","       else","       {","          \/\/ To add and managed others activities","          return false","       }","   }",""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/shareposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/shareposition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Let your users share the position"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Share Position","role":"article","modules":[{"name":"IndoorSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","title":"IndoorModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorModule"}],"abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}],"url":"\/documentation\/indoorsdk\/indoormodule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"role":"article","title":"Outdoor navigation","abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation"},"assDomains.png":{"alt":"Add XcFrame and to section.","type":"image","identifier":"assDomains.png","variants":[{"url":"\/images\/assDomains.png","traits":["1x","light"]}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"role":"article","title":"Geofence","abstract":[{"type":"text","text":"Manage in your app registered region by AENA."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/geofence"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/gettingstarted"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/manageUserActivity(_:andPresentIn:after:prepareToPresent:)":{"role":"symbol","title":"manageUserActivity(_:andPresentIn:after:prepareToPresent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manageUserActivity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andPresentIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"prepareToPresent"},{"kind":"text","text":": () -> ()) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"}"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/manageUserActivity(_:andPresentIn:after:prepareToPresent:)","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormodule\/manageuseractivity(_:andpresentin:after:preparetopresent:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","title":"IndoorMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorMapViewController"}],"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}