{"sections":[],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AirportIsNotReady"}],"title":"OpenCategoryListError.AirportIsNotReady","roleHeading":"Case","role":"symbol","modules":[{"name":"IndoorSDK"}],"externalID":"c:@M@IndoorSDK@E@OpenCategoryListError@OpenCategoryListErrorAirportIsNotReady","navigatorTitle":[{"text":"OpenCategoryListErrorAirportIsNotReady","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/AirportIsNotReady"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirportIsNotReady","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/indoorsdk\/opencategorylisterror\/airportisnotready"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/opencategorylisterror\/airportisnotready"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError":{"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OpenCategoryListError"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}],"title":"OpenCategoryListError"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/AirportIsNotReady":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/AirportIsNotReady","navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListErrorAirportIsNotReady"}],"url":"\/documentation\/indoorsdk\/opencategorylisterror\/airportisnotready","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"AirportIsNotReady","kind":"identifier"}],"role":"symbol","type":"topic","title":"OpenCategoryListError.AirportIsNotReady"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OpenCategoryListErrorAirportIsNotReady"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OpenCategoryListErrorAirportIsNotReady","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OpenCategoryListErrorAirportIsNotReady"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/title","value":"OpenCategoryListError","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/fragments","value":[{"kind":"identifier","text":"OpenCategoryListError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/navigatorTitle","value":[{"text":"OpenCategoryListError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OpenCategoryListErrorAirportIsNotReady","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1AirportIsNotReady\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1AirportIsNotReady\/fragments","value":[{"kind":"identifier","text":"OpenCategoryListErrorAirportIsNotReady"}],"op":"replace"}]}]}