{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CategoryDoNotExist","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/CategoryDoNotExist","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"OpenCategoryListError.CategoryDoNotExist","externalID":"c:@M@IndoorSDK@E@OpenCategoryListError@OpenCategoryListErrorCategoryDoNotExist","modules":[{"name":"IndoorSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CategoryDoNotExist","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListErrorCategoryDoNotExist"}],"roleHeading":"Case","role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/opencategorylisterror\/categorydonotexist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/opencategorylisterror\/categorydonotexist"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror","abstract":[],"title":"OpenCategoryListError","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenCategoryListError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/CategoryDoNotExist":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/CategoryDoNotExist","abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror\/categorydonotexist","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryDoNotExist"}],"navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListErrorCategoryDoNotExist"}],"title":"OpenCategoryListError.CategoryDoNotExist"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"OpenCategoryListErrorCategoryDoNotExist","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OpenCategoryListErrorCategoryDoNotExist"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OpenCategoryListErrorCategoryDoNotExist","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/title","value":"OpenCategoryListError","op":"replace"},{"value":[{"text":"OpenCategoryListError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1CategoryDoNotExist\/title","value":"OpenCategoryListErrorCategoryDoNotExist"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError~1CategoryDoNotExist\/fragments","op":"replace","value":[{"kind":"identifier","text":"OpenCategoryListErrorCategoryDoNotExist"}]}]}]}