{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/localizedDescription"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"property","externalID":"s:9IndoorSDK21OpenCategoryListErrorO20localizedDescriptionSSvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"localizedDescription","modules":[{"name":"IndoorSDK"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/indoorsdk\/opencategorylisterror\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError/localizedDescription":{"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError\/localizedDescription","title":"localizedDescription","role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror\/localizeddescription","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError":{"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OpenCategoryListError"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}],"title":"OpenCategoryListError"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/title","value":"OpenCategoryListError","op":"replace"},{"value":[{"text":"OpenCategoryListError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/navigatorTitle","value":[{"kind":"identifier","text":"OpenCategoryListError"}],"op":"replace"}]}]}