{"hierarchy":{"paths":[[]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"anchor":"Essentials","title":"Essentials"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/AirportInfo","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/BuildingInfo","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Carpark","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/FloorInfo"],"anchor":"Structures","generated":true,"title":"Structures"},{"title":"Variables","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyAccuracy","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBearing","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBuildingId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyFloorId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyIsIndoor","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLatitude","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLongitude"],"anchor":"Variables","generated":true},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/AirportsDBCache","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/BuildingCategory","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/FlightTicketState","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError"],"anchor":"Enumerations"},{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Foundation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/UIKit"],"anchor":"Extended-Modules","generated":true,"title":"Extended Modules"}],"metadata":{"role":"collection","modules":[{"name":"IndoorSDK"}],"title":"IndoorSDK","externalID":"IndoorSDK","roleHeading":"Framework","symbolKind":"module"},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add maps pois and more"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/indoorsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","interfaceLanguage":"swift"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyAccuracy":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyAccuracy","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyaccuracy","role":"symbol","abstract":[{"text":"Accuracy key. Double. Accuracy position in horizontal.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndoorSDKPositionKeyAccuracy","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"IndoorSDKPositionKeyAccuracy","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/ChatbotIntegration":{"role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","type":"topic","kind":"article","url":"\/documentation\/indoorsdk\/chatbotintegration","title":"Chatbot integrations","abstract":[{"type":"text","text":"Improving access to indoor maps functionalities"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation","kind":"article","role":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","title":"Outdoor navigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyBearing":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorSDKPositionKeyBearing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Bearing key. Float. Optional (It could not be).","type":"text"}],"title":"IndoorSDKPositionKeyBearing","type":"topic","navigatorTitle":[{"text":"IndoorSDKPositionKeyBearing","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeybearing","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBearing","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiErrorDomain":{"type":"topic","fragments":[{"text":"OpenPoiErrorDomain","kind":"identifier"}],"title":"OpenPoiErrorDomain","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/openpoierrordomain","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiErrorDomain"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListErrorDomain":{"title":"OpenCategoryListErrorDomain","kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListErrorDomain","fragments":[{"text":"OpenCategoryListErrorDomain","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/opencategorylisterrordomain"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyLatitude":{"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLatitude","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorSDKPositionKeyLatitude"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Latitude key. Double. The longitude of the position."}],"title":"IndoorSDKPositionKeyLatitude","kind":"symbol","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeylatitude","navigatorTitle":[{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/AirportsDBCache":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AirportsDBCache","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/AirportsDBCache","title":"AirportsDBCache","url":"\/documentation\/indoorsdk\/airportsdbcache","abstract":[{"type":"text","text":"Notification object that is posted to the notification center when an"},{"text":" ","type":"text"},{"type":"text","text":"airport is added or delete to the cache data base."}],"navigatorTitle":[{"kind":"identifier","text":"AirportsDBCache"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/BuildingCategory":{"kind":"symbol","title":"BuildingCategory","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/BuildingCategory","abstract":[{"type":"text","text":"Kind of building inside the airport"}],"url":"\/documentation\/indoorsdk\/buildingcategory","type":"topic","role":"symbol","navigatorTitle":[{"text":"BuildingCategory","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BuildingCategory","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenCategoryListError":{"role":"symbol","url":"\/documentation\/indoorsdk\/opencategorylisterror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OpenCategoryListError"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","navigatorTitle":[{"kind":"identifier","text":"OpenCategoryListError"}],"title":"OpenCategoryListError"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/FlightTicketState":{"abstract":[],"url":"\/documentation\/indoorsdk\/flightticketstate","navigatorTitle":[{"kind":"identifier","text":"FlightTicketState"}],"type":"topic","kind":"symbol","title":"FlightTicketState","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/FlightTicketState","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FlightTicketState","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyIsIndoor":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"IndoorSDKPositionKeyIsIndoor","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyIsIndoor","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyisindoor","abstract":[{"text":"Is indoor key. Bool. true = indoor \/ false = outdoor.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyIsIndoor"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyBuildingId":{"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeybuildingid","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorSDKPositionKeyBuildingId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"IndoorSDKPositionKeyBuildingId","abstract":[{"text":"Building identifier key. String. -1 means outdoor (no building).","type":"text"}],"navigatorTitle":[{"text":"IndoorSDKPositionKeyBuildingId","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBuildingId","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"title":"Getting started","url":"\/documentation\/indoorsdk\/gettingstarted","type":"topic","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Geofence":{"abstract":[{"text":"Manage in your app registered region by AENA.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","type":"topic","url":"\/documentation\/indoorsdk\/geofence","kind":"article","title":"Geofence","role":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyFloorId":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyFloorId","abstract":[{"type":"text","text":"Floor identifier key. String. -1 means outdoor, ground floor."}],"kind":"symbol","title":"IndoorSDKPositionKeyFloorId","role":"symbol","url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyfloorid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyFloorId"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Foundation":{"role":"collection","url":"\/documentation\/indoorsdk\/foundation","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Foundation","kind":"symbol","title":"Foundation","type":"topic","abstract":[]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/UIKit":{"url":"\/documentation\/indoorsdk\/uikit","kind":"symbol","title":"UIKit","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/UIKit","abstract":[],"role":"collection"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/Carpark":{"type":"topic","navigatorTitle":[{"text":"Carpark","kind":"identifier"}],"title":"Carpark","abstract":[{"type":"text","text":"This struct represent a carpark saved by the user. IndoorSDK only save one carpark."}],"url":"\/documentation\/indoorsdk\/carpark","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Carpark","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Carpark","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightErrorDomain":{"abstract":[],"url":"\/documentation\/indoorsdk\/createflighterrordomain","title":"CreateFlightErrorDomain","fragments":[{"kind":"identifier","text":"CreateFlightErrorDomain"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightErrorDomain","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","type":"topic","title":"Share Position","url":"\/documentation\/indoorsdk\/shareposition","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","abstract":[{"type":"text","text":"Let your users share the position"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","abstract":[{"text":"Errors creating a Flight, from a dict.","type":"text"}],"title":"CreateFlightError"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/AirportInfo":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/AirportInfo","navigatorTitle":[{"text":"AirportInfo","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/airportinfo","kind":"symbol","abstract":[{"text":"Brief description about the Airport and its structure","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AirportInfo"}],"role":"symbol","type":"topic","title":"AirportInfo"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/FloorInfo":{"abstract":[{"type":"text","text":"Brief description about each floor in the building"}],"title":"FloorInfo","url":"\/documentation\/indoorsdk\/floorinfo","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FloorInfo"}],"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/FloorInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloorInfo"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyLongitude":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLongitude","abstract":[{"text":"Longitude key. Double. The latitude of the position.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeylongitude","title":"IndoorSDKPositionKeyLongitude","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorSDKPositionKeyLongitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"IndoorSDKPositionKeyLongitude","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError":{"navigatorTitle":[{"text":"OpenPoiError","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError","title":"OpenPoiError","abstract":[{"text":"Errors when you try to open a Poi, and it’s not success.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/indoorsdk\/openpoierror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenPoiError","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/BuildingInfo":{"kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/buildinginfo","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BuildingInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Brief description about each building in the airport"}],"title":"BuildingInfo","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/BuildingInfo","navigatorTitle":[{"text":"BuildingInfo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/ChatbotIntegration","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"anchor":"Essentials","title":"Essentials"},{"anchor":"Variables","title":"Variables","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightErrorDomain","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyAccuracy","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBearing","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyBuildingId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyFloorId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyIsIndoor","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLatitude","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyLongitude","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListErrorDomain","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiErrorDomain"]},{"title":"Enumerations","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenCategoryListError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError"],"anchor":"Enumerations","generated":true}]},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyAccuracy\/title","value":"IndoorSDKPositionKeyAccuracy"},{"value":[{"text":"IndoorSDKPositionKeyAccuracy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyAccuracy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyBearing\/title","value":"IndoorSDKPositionKeyBearing"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyBearing\/fragments","value":[{"kind":"identifier","text":"IndoorSDKPositionKeyBearing"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"IndoorMapViewController"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLatitude\/title","value":"IndoorSDKPositionKeyLatitude","op":"replace"},{"value":[{"text":"IndoorSDKPositionKeyLatitude","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLatitude\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/title","value":"OpenCategoryListError","op":"replace"},{"value":[{"kind":"identifier","text":"OpenCategoryListError"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/fragments"},{"value":[{"kind":"identifier","text":"OpenCategoryListError"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenCategoryListError\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyIsIndoor\/title","op":"replace","value":"IndoorSDKPositionKeyIsIndoor"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyIsIndoor\/fragments","op":"replace","value":[{"text":"IndoorSDKPositionKeyIsIndoor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyBuildingId\/title","value":"IndoorSDKPositionKeyBuildingId","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyBuildingId\/fragments","op":"replace","value":[{"text":"IndoorSDKPositionKeyBuildingId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyFloorId\/title","value":"IndoorSDKPositionKeyFloorId","op":"replace"},{"op":"replace","value":[{"text":"IndoorSDKPositionKeyFloorId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyFloorId\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorModule"}]},{"value":"CreateFlightError","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title"},{"value":[{"kind":"identifier","text":"CreateFlightError"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments"},{"value":[{"kind":"identifier","text":"CreateFlightError"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLongitude\/title","op":"replace","value":"IndoorSDKPositionKeyLongitude"},{"value":[{"kind":"identifier","text":"IndoorSDKPositionKeyLongitude"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyLongitude\/fragments"},{"value":"OpenPoiError","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/fragments","value":[{"text":"OpenPoiError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/navigatorTitle","value":[{"text":"OpenPoiError","kind":"identifier"}]}]}]}