{"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiCantBeReach","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError"]]},"variants":[{"paths":["\/documentation\/indoorsdk\/openpoierror\/poicantbereach"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/openpoierror\/poicantbereach"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@IndoorSDK@E@OpenPoiError@OpenPoiErrorPoiCantBeReach","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"OpenPoiErrorPoiCantBeReach","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PoiCantBeReach","kind":"identifier"}],"role":"symbol","title":"OpenPoiError.PoiCantBeReach","modules":[{"name":"IndoorSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoiCantBeReach"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"The poi can’t be reach, usually is a network problem."}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError":{"navigatorTitle":[{"text":"OpenPoiError","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError","title":"OpenPoiError","abstract":[{"text":"Errors when you try to open a Poi, and it’s not success.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/indoorsdk\/openpoierror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenPoiError","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OpenPoiError/PoiCantBeReach":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OpenPoiError\/PoiCantBeReach","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PoiCantBeReach","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenPoiErrorPoiCantBeReach"}],"url":"\/documentation\/indoorsdk\/openpoierror\/poicantbereach","title":"OpenPoiError.PoiCantBeReach","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The poi can’t be reach, usually is a network problem."}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"OpenPoiErrorPoiCantBeReach","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OpenPoiErrorPoiCantBeReach"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OpenPoiErrorPoiCantBeReach"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OpenPoiError","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/fragments","value":[{"text":"OpenPoiError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OpenPoiError"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiCantBeReach\/title","value":"OpenPoiErrorPoiCantBeReach","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1OpenPoiError~1PoiCantBeReach\/fragments","value":[{"text":"OpenPoiErrorPoiCantBeReach","kind":"identifier"}]}]}]}