{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":" "},{"kind":"internalParam","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"err"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"true if the Poi is in the cache. Otherwise return false."}]}]},{"kind":"parameters","parameters":[{"name":"idPoi","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the identifier of the poi to select"}]}]},{"name":"icao","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Icao code of the airport where te Poi is."}]}]},{"name":"readyBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"closure called after requesting the poi to server."}]}]},{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the request return the poi."}]}]},{"name":"err","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error if success is false."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method looks for the Poi in the device cache database. If it finds it, it loads the map with the selected poi and returns true. Otherwise it returns false, and makes the request to catch the info from the servers. After receiving the info from the servers, it excecutes the ready block. If the poi has been found on the servers, the success parametres will be true and the view controller could be pushed, if not, it is false, the error parameter gives the error, and the viewController shouldn’t be pushed."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example of implementation:"}]},{"type":"codeListing","syntax":null,"code":["        let vC = IndoorMapViewController()","if vC.loadPoi(idPoi: idPoi, inAirport: airportIcao, readyBlock: { (success, err) in","   if success {","       \/\/ Remove the activity indicator.","       self.navigationController?.pushViewController(vC, animated: true)","   } else {","       print(err)","       \/\/ Catch info from error and managed.","   }","","}) {","navigationController?.pushViewController(vC, animated: true)","} else {","   \/\/ Present and activity indicator.","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Load the airport with the Poi selected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"err"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"loadPoi(idPoi:inAirport:readyBlock:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@IndoorSDK@objc(cs)IndoorMapViewController(im)loadPoiWithIdPoi:inAirport:readyBlock:","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"seeAlsoSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"role":"symbol","title":"openPoi(idPoi:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Open a POI in a loaded Airpot."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openPoiWithIdPoi:error:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"role":"symbol","title":"loadAirport(icao:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAirport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Load the airport."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"role":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"err"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Load the airport with the Poi selected."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","title":"IndoorMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorMapViewController"}],"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadPoiWithIdPoi:inAirport:readyBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadPoiWithIdPoi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"idPoi"},{"kind":"text","text":" "},{"kind":"identifier","text":"inAirport:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"icao"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool, NSError *)","preciseIdentifier":"c:BFv(#b#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"readyBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","value":"openPoiWithIdPoi:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title","value":"loadAirportWithIcao:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAirportWithIcao:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title","value":"loadPoiWithIdPoi:inAirport:readyBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}