{"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Override Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"cellForItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"title":"collectionView(_:cellForItemAt:)","role":"symbol","externalID":"c:@CM@IndoorSDK@objc(cs)IndoorMapViewController(im)collectionView:cellForItemAtIndexPath:","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"extendedModule":"IndoorSDK","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"IndoorSDK"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UICollectionViewDataSource.collectionView(_:cellForItemAt:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:numberOfItemsInSection:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"title":"collectionView(_:numberOfItemsInSection:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","title":"IndoorSDK","url":"\/documentation\/indoorsdk","type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/UICollectionViewDataSource-Implementations":{"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdatasource-implementations","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations","title":"UICollectionViewDataSource Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillAppear(_:)":{"abstract":[],"kind":"symbol","type":"topic","title":"viewWillAppear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:didSelectItemAt:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:didSelectItemAt:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:didselectitemat:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidLoad()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidload()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/didMove(toParent:)":{"abstract":[],"kind":"symbol","type":"topic","title":"didMove(toParent:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toParent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"didMoveToParentViewController:","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/didmove(toparent:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/traitCollectionDidChange(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"title":"traitCollectionDidChange(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/traitcollectiondidchange(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidAppear(_:)":{"kind":"symbol","type":"topic","abstract":[],"title":"viewDidAppear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidappear(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/accessibilityPerformEscape()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformEscape"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformEscape"}],"title":"accessibilityPerformEscape()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/accessibilityperformescape()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","url":"\/documentation\/indoorsdk\/indoormapviewcontroller","title":"IndoorMapViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"type":"topic","abstract":[{"text":"This class is the visual enter point to IndoorSDK","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:cellForItemAt:)":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:cellForItemAt:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadView()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadView"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"loadView","kind":"identifier"}],"title":"loadView()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadview()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillDisappear(_:)":{"kind":"symbol","type":"topic","abstract":[],"title":"viewWillDisappear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwilldisappear(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"collectionView:cellForItemAtIndexPath:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Override Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"collectionView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItemAtIndexPath:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"collectionView:numberOfItemsInSection:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/title","op":"replace","value":"collectionView:didSelectItemAtIndexPath:"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/fragments","op":"replace"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","value":"didMoveToParentViewController:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didMoveToParentViewController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/title","op":"replace","value":"traitCollectionDidChange:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}]},{"op":"replace","value":"accessibilityPerformEscape","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityPerformEscape","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/fragments"},{"value":"IndoorMapViewController","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"op":"replace"},{"op":"replace","value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/title","value":"loadView","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadView"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}