{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:numberOfItemsInSection:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"anchor":"Override-Methods","generated":true,"title":"Override Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@IndoorSDK@objc(cs)IndoorMapViewController(im)collectionView:numberOfItemsInSection:","title":"collectionView(_:numberOfItemsInSection:)","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"modules":[{"name":"IndoorSDK"}],"extendedModule":"IndoorSDK","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidLoad()":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidload()","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:cellForItemAt:)":{"title":"collectionView(_:cellForItemAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"cellForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/traitCollectionDidChange(_:)":{"title":"traitCollectionDidChange(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/traitcollectiondidchange(_:)","abstract":[],"navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/accessibilityPerformEscape()":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/accessibilityperformescape()","title":"accessibilityPerformEscape()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformEscape"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformEscape"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/didMove(toParent:)":{"title":"didMove(toParent:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toParent"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/didmove(toparent:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"didMoveToParentViewController:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadView()":{"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadView","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"title":"loadView()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadView"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:didSelectItemAt:)":{"title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:didselectitemat:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillDisappear(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","title":"viewWillDisappear(_:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwilldisappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations","title":"UICollectionViewDataSource Implementations","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdatasource-implementations","abstract":[]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"],"generated":true,"title":"Override Methods","anchor":"Override-Methods"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"collectionView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":" *) ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numberOfItemsInSection:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"section","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"value":"collectionView:cellForItemAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/title","op":"replace","value":"traitCollectionDidChange:"},{"value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","op":"replace","value":[{"text":"IndoorMapViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/title","value":"accessibilityPerformEscape","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"accessibilityPerformEscape"}]},{"op":"replace","value":"didMoveToParentViewController:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didMoveToParentViewController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/title","value":"loadView"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadView","kind":"identifier"}]},{"op":"replace","value":"collectionView:didSelectItemAtIndexPath:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/fragments","op":"replace"}]}]}