{"metadata":{"role":"symbol","externalID":"s:9IndoorSDK0A17MapViewControllerC9loadRoute9inAirport13startFromUser6poisIDySS_SbSaySiGtKF","modules":[{"name":"IndoorSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startFromUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"poisID","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"loadRoute(inAirport:startFromUser:poisID:)","platforms":[{"name":"IndoorSDK","introducedAt":"1.4"}],"roleHeading":"Instance Method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Load the airport in pre-route mode with a proposed route to the user"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadRoute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"icao"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"startFromUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"poisID"},{"kind":"text","text":": ["},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"airport ICAO code"}]}],"name":"icao"},{"content":[{"type":"paragraph","inlineContent":[{"text":"set true if you want the route start in user current position.","type":"text"},{"text":" ","type":"text"},{"text":"You must be sure than the user is inside the airport before set as true, an exception will be thrown if the user is not inside the airport","type":"text"}]}],"name":"startFromUser"},{"name":"poisID","content":[{"inlineContent":[{"text":"pois identifier list to visiting. In case the route doesn’t start from user you need at least two origin and destination","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut","isActive":true,"overridingTitle":"loadRouteUserIsOut","overridingTitleInlineContent":[{"type":"text","text":"loadRouteUserIsOut"}]},{"type":"text","text":",  "},{"type":"reference","overridingTitle":"loadRoutePoisNotFound","overridingTitleInlineContent":[{"type":"text","text":"loadRoutePoisNotFound"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","isActive":true},{"text":", ","type":"text"},{"overridingTitleInlineContent":[{"text":"loadRouteAtLeastTwoPoint","type":"text"}],"overridingTitle":"loadRouteAtLeastTwoPoint","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteAtLeastTwoPoint","type":"reference"}],"type":"paragraph"}]},{"type":"heading","anchor":"Example-of-implementation","text":"Example of implementation:","level":2},{"code":["let airportIcao = \"LEMD\"","let pois = [1575062713398, 1237556579858]   \/\/ Others -> 1132835636419, 1132835637997","let vC = IndoorMapViewController()","","do {","   try vC.loadRoute(inAirport: airportIcao, startFromUser: false, poisID: pois)","   navigationController?.pushViewController(vC, animated:  true)","}","catch {","  \/\/ Manage error propertly","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadCarPark(_:)":{"title":"loadCarPark(_:)","abstract":[{"type":"text","text":"Load the airport with the carpark saved selected."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadcarpark(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCarPark"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK7CarparkV","text":"Carpark"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadRoute(inAirport:startFromUser:poisID:)":{"title":"loadRoute(inAirport:startFromUser:poisID:)","abstract":[{"type":"text","text":"Load the airport in pre-route mode with a proposed route to the user"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadRoute"},{"text":"(","kind":"text"},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"startFromUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"poisID","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoadOptionError"}],"abstract":[{"type":"text","text":"Errors than could happen when you try to load an airport with some options"}],"title":"IndoorMapViewController.LoadOptionError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoadOptionError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"title":"IndoorMapViewController","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"This class is the visual enter point to IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","url":"\/documentation\/indoorsdk\/indoormapviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"title":"openPoi(idPoi:)","abstract":[{"type":"text","text":"Open a POI in a loaded Airpot."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openPoi","kind":"identifier"},{"kind":"text","text":"("},{"text":"idPoi","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)","abstract":[{"text":"Load the airport with the Poi selected.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadPoi"},{"text":"(","kind":"text"},{"text":"idPoi","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"success"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"err","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"kind":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRouteUserIsOut":{"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteuserisout","title":"IndoorMapViewController.LoadOptionError.loadRouteUserIsOut","kind":"symbol","abstract":[{"type":"text","text":"route checked as user origin but the user is not inside the airport"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadRouteUserIsOut","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRouteAtLeastTwoPoint":{"kind":"symbol","abstract":[{"text":"There is not enough points to make a route","type":"text"}],"title":"IndoorMapViewController.LoadOptionError.loadRouteAtLeastTwoPoint","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"loadRouteAtLeastTwoPoint","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteAtLeastTwoPoint","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteatleasttwopoint"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"type":"topic","abstract":[{"type":"text","text":"Load the airport."}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)","title":"loadAirport(icao:)","navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAirport"},{"kind":"text","text":"("},{"text":"icao","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)":{"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"type":"text","text":" "},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"type":"text","text":"You should also specifier witch building and floor to focus."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadAirport","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withFilterCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"focusedIn"},{"kind":"text","text":": ("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","op":"replace","value":[{"text":"IndoorMapViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","value":"openPoiWithIdPoi:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"openPoiWithIdPoi:error:","kind":"identifier"}]},{"op":"replace","value":"loadPoiWithIdPoi:inAirport:readyBlock:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title","value":"loadAirportWithIcao:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAirportWithIcao:"}]}]}]}