{"sections":[],"kind":"symbol","abstract":[{"text":"Errors than could happen when you try to load an airport with some options","type":"text"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","interfaceLanguage":"swift"},"metadata":{"externalID":"s:9IndoorSDK0A17MapViewControllerC15LoadOptionErrorO","modules":[{"name":"IndoorSDK"}],"title":"IndoorMapViewController.LoadOptionError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoadOptionError"}],"navigatorTitle":[{"kind":"identifier","text":"LoadOptionError"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol"},"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadCategoryNotFound","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteAtLeastTwoPoint","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRoutePoisNotFound(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/Error-Implementations"],"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.geographica.IndoorSDK\/s5ErrorP","doc:\/\/com.geographica.IndoorSDK\/s8SendableP"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoadOptionError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/s8SendableP":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRouteAtLeastTwoPoint":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadRouteAtLeastTwoPoint"}],"title":"IndoorMapViewController.LoadOptionError.loadRouteAtLeastTwoPoint","abstract":[{"text":"There is not enough points to make a route","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteatleasttwopoint","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteAtLeastTwoPoint"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadCategoryNotFound":{"role":"symbol","title":"IndoorMapViewController.LoadOptionError.loadCategoryNotFound","abstract":[{"type":"text","text":"The category is not found in the Indoor Mobile DB"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadcategorynotfound","type":"topic","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadCategoryNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadCategoryNotFound","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRouteUserIsOut":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRouteUserIsOut","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadRouteUserIsOut"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadrouteuserisout","kind":"symbol","title":"IndoorMapViewController.LoadOptionError.loadRouteUserIsOut","type":"topic","abstract":[{"type":"text","text":"route checked as user origin but the user is not inside the airport"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError":{"title":"IndoorMapViewController.LoadOptionError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadOptionError"}],"role":"symbol","navigatorTitle":[{"text":"LoadOptionError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Errors than could happen when you try to load an airport with some options"}],"type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadRoutePoisNotFound(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Some poi is not found in the Indoor Mobile DB, several things could happen, the airport is not downloaded, some identifiers are wrong…"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadRoutePoisNotFound(_:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadroutepoisnotfound(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadRoutePoisNotFound"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"])"}],"title":"IndoorMapViewController.LoadOptionError.loadRoutePoisNotFound(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/Error-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/Error-Implementations","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/error-implementations"},"doc://com.geographica.IndoorSDK/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.geographica.IndoorSDK\/s5ErrorP"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"IndoorMapViewController","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}