{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Load the airport.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"icao"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"IndoorSDK"}],"externalID":"c:@M@IndoorSDK@objc(cs)IndoorMapViewController(im)loadAirportWithIcao:","roleHeading":"Instance Method","title":"loadAirport(icao:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)"],"generated":true,"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"icao"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"icao","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Airport icao to open"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should call this before add IndoorMapViewController"},{"type":"text","text":" "},{"text":"to a navigationController","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"type":"topic","abstract":[{"type":"text","text":"Load the airport."}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)","title":"loadAirport(icao:)","navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAirport"},{"kind":"text","text":"("},{"text":"icao","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)","abstract":[{"text":"Load the airport with the Poi selected.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadPoi"},{"text":"(","kind":"text"},{"text":"idPoi","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"success"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"err","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"kind":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"title":"openPoi(idPoi:)","abstract":[{"type":"text","text":"Open a POI in a loaded Airpot."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openPoi","kind":"identifier"},{"kind":"text","text":"("},{"text":"idPoi","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)":{"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"type":"text","text":" "},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"type":"text","text":"You should also specifier witch building and floor to focus."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadAirport","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withFilterCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"focusedIn"},{"kind":"text","text":": ("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadCarPark(_:)":{"title":"loadCarPark(_:)","abstract":[{"type":"text","text":"Load the airport with the carpark saved selected."}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadcarpark(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCarPark"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9IndoorSDK7CarparkV","text":"Carpark"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"title":"IndoorMapViewController","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"This class is the visual enter point to IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","url":"\/documentation\/indoorsdk\/indoormapviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadRoute(inAirport:startFromUser:poisID:)":{"title":"loadRoute(inAirport:startFromUser:poisID:)","abstract":[{"type":"text","text":"Load the airport in pre-route mode with a proposed route to the user"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadRoute"},{"text":"(","kind":"text"},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"startFromUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"poisID","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"loadAirportWithIcao:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAirportWithIcao:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"]}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"loadAirportWithIcao:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"icao","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"loadAirportWithIcao:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAirportWithIcao:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title","value":"loadPoiWithIdPoi:inAirport:readyBlock:"},{"value":[{"kind":"text","text":"- "},{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments","op":"replace"},{"value":"openPoiWithIdPoi:error:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openPoiWithIdPoi:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments"},{"value":"IndoorMapViewController","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title"},{"value":[{"text":"IndoorMapViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}