{"seeAlsoSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAirport"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"icao","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"withFilterCategory","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subsId","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"focusedIn"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"terAndFloor"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"icao","content":[{"inlineContent":[{"type":"text","text":"Airport ICAO code"}],"type":"paragraph"}]},{"name":"id","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category identifier"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Subcategory identifiers list (empty list means all subcategories)"}],"type":"paragraph"}],"name":"subsId"},{"name":"terAndFloor","content":[{"inlineContent":[{"text":"Dupla with building identifier and floor identifier","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Example of implementation:","anchor":"Example-of-implementation","level":2},{"syntax":"swift","code":["       let vC = IndoorMapViewController()","do {","   try vC.loadAirport(\"LEMD\", withFilterCategory: 8, focusedIn: (342804, 5))","   navigationController?.pushViewController(vC, animated: true)","}","catch","{","   \/\/ Manage error propertly","}"],"type":"codeListing"},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"text":"","type":"text"},{"overridingTitle":"loadCategoryNotFound","overridingTitleInlineContent":[{"text":"loadCategoryNotFound","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadCategoryNotFound","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)"]}],"abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"text":" ","type":"text"},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"text":"You should also specifier witch building and floor to focus.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"s:9IndoorSDK0A17MapViewControllerC11loadAirport_18withFilterCategory16andSubcategories9focusedInySS_SiSaySiGSi_SitSgtKF","modules":[{"name":"IndoorSDK"}],"platforms":[{"name":"IndoorSDK","introducedAt":"1.4","beta":false}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withFilterCategory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"], ","kind":"text"},{"text":"focusedIn","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)"},"kind":"symbol","references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"withFilterCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"andSubcategories","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"], ","kind":"text"},{"text":"focusedIn","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(_:withfiltercategory:andsubcategories:focusedin:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(_:withFilterCategory:andSubcategories:focusedIn:)","kind":"symbol","abstract":[{"type":"text","text":"Load an Airport with a category filter and optionally subcategories too."},{"text":" ","type":"text"},{"type":"text","text":"With this filter only the pois of these subcategories will be show."},{"text":" ","type":"text"},{"text":"You should also specifier witch building and floor to focus.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadRoute(inAirport:startFromUser:poisID:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadRoute(inAirport:startFromUser:poisID:)","title":"loadRoute(inAirport:startFromUser:poisID:)","kind":"symbol","type":"topic","abstract":[{"text":"Load the airport in pre-route mode with a proposed route to the user","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadroute(inairport:startfromuser:poisid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"startFromUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"poisID","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","type":"topic","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller","kind":"symbol","title":"IndoorMapViewController","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"navigatorTitle":[{"text":"openPoiWithIdPoi:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","abstract":[{"text":"Open a POI in a loaded Airpot.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)","role":"symbol","title":"openPoi(idPoi:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadCarPark(_:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadCarPark(_:)","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadcarpark(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadCarPark"},{"kind":"text","text":"("},{"preciseIdentifier":"s:9IndoorSDK7CarparkV","kind":"typeIdentifier","text":"Carpark"},{"kind":"text","text":")"}],"kind":"symbol","title":"loadCarPark(_:)","abstract":[{"text":"Load the airport with the carpark saved selected.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadPoi","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"err","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}],"kind":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)","abstract":[{"text":"Load the airport with the Poi selected.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAirport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"icao","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Load the airport.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)","role":"symbol","title":"loadAirport(icao:)","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/LoadOptionError/loadCategoryNotFound":{"role":"symbol","title":"IndoorMapViewController.LoadOptionError.loadCategoryNotFound","abstract":[{"type":"text","text":"The category is not found in the Indoor Mobile DB"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadoptionerror\/loadcategorynotfound","type":"topic","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/LoadOptionError\/loadCategoryNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadCategoryNotFound","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"value":[{"kind":"identifier","text":"IndoorMapViewController"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/navigatorTitle","op":"replace","value":[{"text":"IndoorMapViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","op":"replace","value":"openPoiWithIdPoi:error:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"openPoiWithIdPoi:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title","value":"loadPoiWithIdPoi:inAirport:readyBlock:","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"loadPoiWithIdPoi:inAirport:readyBlock:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title","value":"loadAirportWithIcao:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAirportWithIcao:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}