{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"idPoi","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the identifier of the poi to select"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method only has effect if the IndoorMapViewController is"},{"type":"text","text":" "},{"type":"text","text":"loaded."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"OpenPoiError.PoiDontExist"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"if "},{"type":"codeVoice","code":"idPoi"},{"type":"text","text":" doesn’t match with"},{"type":"text","text":" "},{"type":"text","text":"current Pois in DB."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Open a POI in a loaded Airpot."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"openPoi(idPoi:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@IndoorSDK@objc(cs)IndoorMapViewController(im)openPoiWithIdPoi:error:","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"seeAlsoSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/openPoi(idPoi:)":{"role":"symbol","title":"openPoi(idPoi:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Open a POI in a loaded Airpot."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/openPoi(idPoi:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openPoiWithIdPoi:error:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/openpoi(idpoi:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","title":"IndoorMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorMapViewController"}],"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadAirport(icao:)":{"role":"symbol","title":"loadAirport(icao:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAirport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Load the airport."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadAirportWithIcao:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadairport(icao:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadPoi(idPoi:inAirport:readyBlock:)":{"role":"symbol","title":"loadPoi(idPoi:inAirport:readyBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPoi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idPoi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyBlock"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"err"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Load the airport with the Poi selected."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadpoi(idpoi:inairport:readyblock:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"openPoiWithIdPoi:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadAirport(icao:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadPoi(idPoi:inAirport:readyBlock:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"openPoiWithIdPoi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"idPoi"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/title","value":"openPoiWithIdPoi:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1openPoi(idPoi:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openPoiWithIdPoi:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/title","value":"loadAirportWithIcao:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadAirport(icao:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAirportWithIcao:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/title","value":"loadPoiWithIdPoi:inAirport:readyBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadPoi(idPoi:inAirport:readyBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadPoiWithIdPoi:inAirport:readyBlock:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}