{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"metadata":{"modules":[{"name":"IndoorSDK"}],"title":"UICollectionViewDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/UICollectionViewDataSource-Implementations"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/uicollectionviewdatasource-implementations"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","url":"\/documentation\/indoorsdk\/indoormapviewcontroller","title":"IndoorMapViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"type":"topic","abstract":[{"text":"This class is the visual enter point to IndoorSDK","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:cellForItemAt:)":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"title":"collectionView(_:cellForItemAt:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","title":"IndoorSDK","url":"\/documentation\/indoorsdk","type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:numberOfItemsInSection:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"title":"collectionView(_:numberOfItemsInSection:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"IndoorMapViewController","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}],"op":"replace"},{"value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/title","op":"replace","value":"collectionView:numberOfItemsInSection:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}