{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"]]},"metadata":{"modules":[{"name":"IndoorSDK"}],"title":"viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@IndoorSDK@objc(cs)IndoorMapViewController(im)viewWillAppear:","roleHeading":"Instance Method","role":"symbol","extendedModule":"IndoorSDK","symbolKind":"method","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}]},"kind":"symbol","sections":[],"seeAlsoSections":[{"title":"Override Methods","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidAppear(_:)":{"abstract":[],"title":"viewDidAppear(_:)","kind":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/didMove(toParent:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didMoveToParentViewController:"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/didmove(toparent:)","type":"topic","title":"didMove(toParent:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toParent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:numberOfItemsInSection:)":{"kind":"symbol","navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:numberofitemsinsection:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","title":"collectionView(_:numberOfItemsInSection:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:cellForItemAt:)":{"kind":"symbol","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:cellforitemat:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","title":"collectionView(_:cellForItemAt:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell","kind":"typeIdentifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/accessibilityPerformEscape()":{"abstract":[],"title":"accessibilityPerformEscape()","kind":"symbol","navigatorTitle":[{"text":"accessibilityPerformEscape","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/accessibilityperformescape()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessibilityPerformEscape","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillDisappear(_:)":{"kind":"symbol","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwilldisappear(_:)","type":"topic","title":"viewWillDisappear(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"title":"IndoorMapViewController","navigatorTitle":[{"text":"IndoorMapViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"This class is the visual enter point to IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","url":"\/documentation\/indoorsdk\/indoormapviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndoorMapViewController"}],"kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/loadView()":{"abstract":[],"title":"loadView()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadView"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/loadview()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadView"},{"text":"()","kind":"text"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewDidLoad()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"role":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewdidload()","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","title":"viewDidLoad()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillAppear(_:)","role":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/viewwillappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/collectionView(_:didSelectItemAt:)":{"type":"topic","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/collectionview(_:didselectitemat:)","title":"collectionView(_:didSelectItemAt:)","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)","navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController/traitCollectionDidChange(_:)":{"kind":"symbol","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormapviewcontroller\/traitcollectiondidchange(_:)","title":"traitCollectionDidChange(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier","text":"UITraitCollection"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"viewWillAppear:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"title":"Override Methods","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/loadView()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidLoad()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewDidAppear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/viewWillDisappear(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/accessibilityPerformEscape()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/traitCollectionDidChange(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/didMove(toParent:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:cellForItemAt:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController\/collectionView(_:didSelectItemAt:)"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"viewWillAppear:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewDidAppear:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidAppear(_:)\/fragments"},{"op":"replace","value":"didMoveToParentViewController:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1didMove(toParent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToParentViewController:","kind":"identifier"}],"op":"replace"},{"value":"collectionView:numberOfItemsInSection:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}]},{"op":"replace","value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:cellForItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}]},{"op":"replace","value":"accessibilityPerformEscape","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1accessibilityPerformEscape()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformEscape"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillDisappear(_:)\/fragments"},{"value":"IndoorMapViewController","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"text":"IndoorMapViewController","kind":"identifier"}]},{"value":"loadView","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1loadView()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadView"}]},{"op":"replace","value":"viewDidLoad","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1viewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1collectionView(_:didSelectItemAt:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}