{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind\/subtract(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/usernotificationkind\/subtract(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind\/SetAlgebra-Implementations"]]},"metadata":{"role":"symbol","externalID":"s:s10SetAlgebraPsE8subtractyyxF::SYNTHESIZED::s:9IndoorSDK0A6ModuleC20UserNotificationKindV","modules":[{"name":"IndoorSDK","relatedModules":["Swift"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtract"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"subtract(_:)","extendedModule":"Swift","roleHeading":"Instance Method","symbolKind":"method"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SetAlgebra.subtract(_:)"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/UserNotificationKind/subtract(_:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind\/subtract(_:)","title":"subtract(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/usernotificationkind\/subtract(_:)","type":"topic","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/UserNotificationKind/SetAlgebra-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind\/SetAlgebra-Implementations","url":"\/documentation\/indoorsdk\/indoormodule\/usernotificationkind\/setalgebra-implementations","abstract":[],"title":"SetAlgebra Implementations","kind":"article","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/UserNotificationKind":{"abstract":[{"type":"text","text":"In AENA App users could chose receive info inside three different category, operational, commercial and third parties. This element represent these categories in order of the App info to IndoorSDK about user selection."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"UserNotificationKind","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/usernotificationkind","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/UserNotificationKind","navigatorTitle":[{"kind":"identifier","text":"UserNotificationKind"}],"title":"IndoorModule.UserNotificationKind","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","op":"replace","value":"IndoorModule"},{"value":[{"text":"IndoorModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments"},{"value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}