{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This functionality allow AENA to register several regions to alert user enter on it about useful commercial, operational of third parties information."},{"type":"text","text":" "},{"type":"text","text":"When the map is on screen the whole functionality is manage by IndoorSDK. When the App is in foreground but the map is not on screen the info is passed to the App in other to manage it."}]},{"anchor":"Provide-info-about-user-notification-settings","level":2,"type":"heading","text":"Provide info about user notification settings"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To provide info about your user settings use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/userActiveNotifications(_:)"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example of implementation:"}]},{"type":"codeListing","syntax":"swift","code":["IndoorModule.shared.userActiveNotifications([.operational, .commercial])"]},{"anchor":"Where-and-how-manage-this-alerts","level":2,"type":"heading","text":"Where and how manage this alerts"},{"type":"paragraph","inlineContent":[{"type":"text","text":"IndoorSDK provide in its class "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},{"type":"text","text":" a function "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/enterInGeofenceAction"},{"type":"text","text":" to add your code."},{"type":"text","text":" "},{"type":"text","text":"Every time the user enter in a region, the function "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/enterInGeofenceAction"},{"type":"text","text":" will be call, this function  return a boolean with true if the info has been show to the user or false if not."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example of implementation:"}]},{"type":"codeListing","syntax":"swift","code":["IndoorModule.shared.enterInGeofenceAction = { (geoNew: IndoorModule.GeofenceNew) -> Bool in","    ","    if self.showGeofencesNot","    {","        let alertVC = UIAlertController(title: geoNew.name, message: geoNew.message, preferredStyle: .alert)","        alertVC.addAction(UIAlertAction(title: \"ok\", style: .default, handler: nil))","        self.present(alertVC, animated: true, completion: nil)","        ","        return true","    }","    else","    {","        return false","    }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/geofence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/geofence"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/Geofence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manage in your app registered region by AENA."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Geofence","role":"article","modules":[{"name":"IndoorSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/userActiveNotifications(_:)":{"role":"symbol","title":"userActiveNotifications(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userActiveNotifications"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserNotificationKind","preciseIdentifier":"s:9IndoorSDK0A6ModuleC20UserNotificationKindV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this to set the user notifications selection."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/userActiveNotifications(_:)","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormodule\/useractivenotifications(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","title":"IndoorModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorModule"}],"abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}],"url":"\/documentation\/indoorsdk\/indoormodule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/OutdoorNavigation":{"role":"article","title":"Outdoor navigation","abstract":[{"type":"text","text":"Combine outdoor navigation with dedicated Apps with IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/outdoornavigation"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorMapViewController":{"role":"symbol","title":"IndoorMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorMapViewController"}],"abstract":[{"type":"text","text":"This class is the visual enter point to IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorMapViewController"}],"url":"\/documentation\/indoorsdk\/indoormapviewcontroller"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/GettingStarted":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"Add IndoorSDK to your app."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/gettingstarted"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/enterInGeofenceAction":{"role":"symbol","title":"enterInGeofenceAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterInGeofenceAction"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GeofenceNew","preciseIdentifier":"s:9IndoorSDK0A6ModuleC11GeofenceNewV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Function to manage Geofence functionality"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/enterInGeofenceAction","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/indoormodule\/enteringeofenceaction"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/SharePosition":{"role":"article","title":"Share Position","abstract":[{"type":"text","text":"Let your users share the position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","kind":"article","type":"topic","url":"\/documentation\/indoorsdk\/shareposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/GettingStarted","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/SharePosition","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/OutdoorNavigation","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorMapViewController"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/title","value":"IndoorMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorMapViewController\/fragments","value":[{"kind":"identifier","text":"IndoorMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}