{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyaccuracy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoorsdkpositionkeyaccuracy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyAccuracy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Accuracy key. Double. Accuracy position in horizontal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"IndoorSDKPositionKeyAccuracy","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@IndoorSDKPositionKeyAccuracy","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorSDKPositionKeyAccuracy":{"role":"symbol","title":"IndoorSDKPositionKeyAccuracy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Accuracy key. Double. Accuracy position in horizontal."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorSDKPositionKeyAccuracy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}],"url":"\/documentation\/indoorsdk\/indoorsdkpositionkeyaccuracy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"IndoorSDKPositionKeyAccuracy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyAccuracy\/title","value":"IndoorSDKPositionKeyAccuracy"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorSDKPositionKeyAccuracy\/fragments","value":[{"kind":"identifier","text":"IndoorSDKPositionKeyAccuracy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}