{"seeAlsoSections":[{"title":"Deprecated","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"anchor":"Deprecated"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/action"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"roleHeading":"Instance Property","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(py)action","title":"action","navigatorTitle":[{"text":"action","kind":"identifier"}],"symbolKind":"property","role":"symbol","platforms":[],"modules":[{"name":"IndoorSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Important","type":"heading","text":"Important"},{"inlineContent":[{"text":"´Deprecated´action is never call","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Action to be excecute when the "},{"type":"codeVoice","code":"flight info"},{"text":" ","type":"text"},{"text":"button is pressed.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/action":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"title":"action","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Action to be excecute when the "},{"type":"codeVoice","code":"flight info"},{"text":" ","type":"text"},{"type":"text","text":"button is pressed."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","url":"\/documentation\/indoorsdk\/indoormodule\/action"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getPosition()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPosition"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"title":"getPosition()","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"User last position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getposition()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setPMR(_:)":{"type":"topic","abstract":[{"type":"text","text":"Switch On\/Off the "},{"type":"strong","inlineContent":[{"text":"PRM","type":"text"}]},{"type":"text","text":" routes"},{"type":"text","text":" "},{"type":"text","text":"(People Reduced Mobility)"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","role":"symbol","title":"setPMR(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPMR:"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlightInfo(_:)":{"type":"topic","abstract":[{"type":"text","text":"Set the info about the flight."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","role":"symbol","title":"setFlightInfo(_:)","kind":"symbol","navigatorTitle":[{"text":"setFlightInfo:","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlightInfo"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"action","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"action","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Deprecated","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"anchor":"Deprecated"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:BFv()","kind":"typeIdentifier","text":"void (^)(void)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/fragments","value":[{"text":"action","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/title","value":"getPosition","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"value":[{"text":"IndoorModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle"},{"op":"replace","value":"setPMR:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPMR:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/title","op":"replace","value":"setFlightInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setFlightInfo:"}]}]}]}