{"metadata":{"navigatorTitle":[{"text":"airportIsCached:","kind":"identifier"}],"externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)airportIsCached:","symbolKind":"method","roleHeading":"Instance Method","title":"airportIsCached(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"IndoorSDK"}]},"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"airportIsCached"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"icao","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"airport icao"}],"type":"paragraph"}],"name":"icao"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"true if the airport is in cache. False if it’s not."}]}]}],"sections":[],"abstract":[{"type":"text","text":"To ask if an airport is ready"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"title":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getUserPosition()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPosition"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUserPosition"}],"abstract":[{"text":"User last position","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","title":"getUserPosition()","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/getuserposition()","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlight(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFlight","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"setFlight:error:","kind":"identifier"}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","title":"setFlight(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/setflight(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/airportIsCached(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"airportIsCached:"}],"abstract":[{"text":"To ask if an airport is ready","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","title":"airportIsCached(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadSaveParking(inAirport:inNavController:action:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadSaveParking","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAirport","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inNavController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}],"abstract":[{"text":"Open the save carpark screen inside the provide navigation controller.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)","title":"loadSaveParking(inAirport:inNavController:action:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/loadsaveparking(inairport:innavcontroller:action:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","url":"\/documentation\/indoorsdk\/indoormodule\/positionkey","abstract":[{"text":"Define the constanst keys of the position dictionary.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositionKey"}],"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"kind":"symbol","title":"IndoorModule.PositionKey"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadCategory(_:inAirport:inNavController:action:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadCategory","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": (([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","title":"loadCategory(_:inAirport:inNavController:action:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"airportIsCached:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"airportIsCached:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"title":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"airportIsCached:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"icao"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"IndoorModule","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/title","value":"getUserPosition"},{"value":[{"text":"- ","kind":"text"},{"text":"getUserPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/title","value":"setFlight:error:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setFlight:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/title","value":"airportIsCached:"},{"value":[{"text":"- ","kind":"text"},{"text":"airportIsCached:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/title","op":"replace","value":"loadSaveParkingInAirport:inNavController:error:action:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadSaveParkingInAirport:inNavController:error:action:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/title","op":"replace","value":"loadCategory:inAirport:inNavController:error:action:"},{"value":[{"kind":"text","text":"- "},{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}