{"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/getposition()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/getposition()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"User last position"}],"sections":[],"metadata":{"modules":[{"name":"IndoorSDK"}],"title":"getPosition()","symbolKind":"method","navigatorTitle":[{"text":"getPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"platforms":[],"roleHeading":"Instance Method","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)getPosition","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"title":"Deprecated"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Position in a SITPoint (Situm position object)"},{"text":" ","type":"text"},{"text":"or nil if there is not position.","type":"text"}],"type":"paragraph"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"If you have called start(), you should always have a position, but keep in mind that Situm’s framework gives you a position both when the user is inside or outside an airport.","type":"text"}]},{"text":"Important","type":"heading","anchor":"Important","level":2},{"inlineContent":[{"text":"You must to call start() before this method.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"##Deprecated: use getUserPosition always return nothing (nil)","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","interfaceLanguage":"swift"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getPosition()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPosition"},{"text":"() -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"getPosition","kind":"identifier"}],"abstract":[{"text":"User last position","type":"text"}],"deprecated":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","title":"getPosition()","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/getposition()","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlightInfo(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFlightInfo"},{"text":"([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"role":"symbol","navigatorTitle":[{"text":"setFlightInfo:","kind":"identifier"}],"abstract":[{"text":"Set the info about the flight.","type":"text"}],"deprecated":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","title":"setFlightInfo(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setPMR(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPMR","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"setPMR:","kind":"identifier"}],"abstract":[{"text":"Switch On\/Off the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"PRM"}]},{"type":"text","text":" routes"},{"text":" ","type":"text"},{"text":"(People Reduced Mobility)","type":"text"}],"deprecated":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","title":"setPMR(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/action":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"role":"symbol","navigatorTitle":[{"text":"action","kind":"identifier"}],"abstract":[{"text":"Action to be excecute when the ","type":"text"},{"code":"flight info","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"button is pressed."}],"deprecated":true,"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","title":"action","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/action","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"getPosition","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getPosition","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"generated":true,"title":"Deprecated"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"getPosition","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"IndoorModule","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments"},{"value":"getPosition","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPosition"}]},{"value":"setFlightInfo:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFlightInfo:"}]},{"op":"replace","value":"setPMR:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPMR:"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/title","op":"replace","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/fragments","value":[{"text":"action","kind":"identifier"}]}]}]}