{"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCategory"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"idCat","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"icao"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?) "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Category id","type":"text"}],"type":"paragraph"}],"name":"idCat"},{"name":"icao","content":[{"inlineContent":[{"type":"text","text":"Airport icao"}],"type":"paragraph"}]},{"name":"inNavController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Navigation controller"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Action to manage the selection or nil to open map"}]}],"name":"action"}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"When you select a POI in the list (or detail view) two things can happen. If the action parameter is nil, the pressed POI is open in the map at the same time the view list is poped. If the action parameter is not nil the view list is poped of the navigation controller and the action is fired.","type":"text"},{"type":"text","text":" "},{"text":"All of these happen if the airport is cached. Other case an error is throw.","type":"text"}]},{"style":"note","name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error if airport i\/Users\/joaquinpbarroso\/Documents\/AENA\/ios\/IndoorSDK\/Position\/Location.swift:    func buildingContainsPoint(lon: Double, lat: Double) -> _Building?s not in cache"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"title":"loadCategory(_:inAirport:inNavController:action:)","symbolKind":"method","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)loadCategory:inAirport:inNavController:error:action:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inNavController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":", "},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"}],"role":"symbol","modules":[{"name":"IndoorSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"seeAlsoSections":[{"title":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"anchor":"Utils","generated":true}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadCategory(_:inAirport:inNavController:action:)":{"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)","navigatorTitle":[{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","title":"loadCategory(_:inAirport:inNavController:action:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCategory"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"text":": (([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getUserPosition()":{"type":"topic","navigatorTitle":[{"text":"getUserPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"User last position"}],"kind":"symbol","title":"getUserPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getuserposition()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserPosition"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/airportIsCached(_:)":{"url":"\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)","navigatorTitle":[{"kind":"identifier","text":"airportIsCached:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"To ask if an airport is ready"}],"title":"airportIsCached(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey","kind":"symbol","title":"IndoorModule.PositionKey","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositionKey"}],"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"abstract":[{"text":"Define the constanst keys of the position dictionary.","type":"text"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlight(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlight"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflight(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","title":"setFlight(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFlight:error:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadSaveParking(inAirport:inNavController:action:)":{"title":"loadSaveParking(inAirport:inNavController:action:)","role":"symbol","abstract":[{"type":"text","text":"Open the save carpark screen inside the provide navigation controller."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)","url":"\/documentation\/indoorsdk\/indoormodule\/loadsaveparking(inairport:innavcontroller:action:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadSaveParking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"loadCategory:inAirport:inNavController:error:action:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"anchor":"Utils","generated":true}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"loadCategory:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"idCat","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inAirport:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"icao","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inNavController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":" *) "},{"text":"inNavController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":" ","kind":"text"},{"text":"action:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Category id","type":"text"}]}],"name":"idCat"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Airport icao"}]}],"name":"icao"},{"name":"inNavController","content":[{"inlineContent":[{"text":"Navigation controller","type":"text"}],"type":"paragraph"}]},{"name":"action","content":[{"inlineContent":[{"text":"Action to manage the selection or nil to open map","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":"IndoorModule","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"text":"IndoorModule","kind":"identifier"}]},{"value":[{"text":"IndoorModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle"},{"op":"replace","value":"loadCategory:inAirport:inNavController:error:action:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/title","value":"getUserPosition"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getUserPosition"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/title","value":"airportIsCached:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"airportIsCached:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/fragments"},{"value":"setFlight:error:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setFlight:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/title","op":"replace","value":"loadSaveParkingInAirport:inNavController:error:action:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadSaveParkingInAirport:inNavController:error:action:"}]}]}]}