{"abstract":[{"type":"text","text":"Define the constanst keys of the position dictionary."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PositionKey","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"externalID":"s:9IndoorSDK0A6ModuleC11PositionKeyV","symbolKind":"struct","roleHeading":"Structure","title":"IndoorModule.PositionKey","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PositionKey"}],"modules":[{"name":"IndoorSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/positionkey"]}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"topicSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/accuracy","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/bearing","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/buildingId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/floorId","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/isIndoor","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/latitude","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/longitude"],"title":"Type Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"title":"Utils"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/buildingId":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/buildingid","abstract":[{"text":"Building identifier key. String. -1 means outdoor (no building).","type":"text"}],"type":"topic","title":"buildingId","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/buildingId","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getUserPosition()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPosition"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUserPosition"}],"abstract":[{"text":"User last position","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","title":"getUserPosition()","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/getuserposition()","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlight(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFlight","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"setFlight:error:","kind":"identifier"}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","title":"setFlight(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/setflight(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/longitude":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/longitude","abstract":[{"type":"text","text":"Longitude key. Double. The latitude of the position."}],"type":"topic","title":"longitude","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"longitude","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/longitude"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/accuracy":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/accuracy","abstract":[{"text":"Accuracy key. Double. Accuracy position in horizontal.","type":"text"}],"type":"topic","title":"accuracy","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/accuracy","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/floorId":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/floorid","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/floorId","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Floor identifier key. String."}],"title":"floorId"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/latitude":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/latitude","title":"latitude","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"latitude"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/latitude","abstract":[{"text":"Latitude key. Double. The longitude of the position.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/bearing":{"type":"topic","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/bearing","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"bearing","abstract":[{"type":"text","text":"Bearing key. Float. Optional (It could not be)."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/bearing"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadCategory(_:inAirport:inNavController:action:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadCategory","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": (([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"loadCategory:inAirport:inNavController:error:action:","kind":"identifier"}],"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","title":"loadCategory(_:inAirport:inNavController:action:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/airportIsCached(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"airportIsCached:"}],"abstract":[{"text":"To ask if an airport is ready","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","title":"airportIsCached(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","url":"\/documentation\/indoorsdk\/indoormodule\/positionkey","abstract":[{"text":"Define the constanst keys of the position dictionary.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositionKey"}],"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"kind":"symbol","title":"IndoorModule.PositionKey"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey/isIndoor":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey\/isIndoor","title":"isIndoor","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isIndoor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/positionkey\/isindoor","abstract":[{"text":"Is indoor key. Bool. true = indoor \/ false = outdoor.","type":"text"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadSaveParking(inAirport:inNavController:action:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadSaveParking","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAirport","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inNavController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}],"abstract":[{"text":"Open the save carpark screen inside the provide navigation controller.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)","title":"loadSaveParking(inAirport:inNavController:action:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/loadsaveparking(inairport:innavcontroller:action:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/title","value":"getUserPosition"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/title","value":"setFlight:error:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setFlight:error:","kind":"identifier"}]},{"value":"IndoorModule","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace"},{"value":"loadCategory:inAirport:inNavController:error:action:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/title","value":"airportIsCached:"},{"value":[{"kind":"text","text":"- "},{"text":"airportIsCached:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/fragments"},{"value":"loadSaveParkingInAirport:inNavController:error:action:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadSaveParkingInAirport:inNavController:error:action:"}]}]}]}