{"metadata":{"externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)requestAirportsInfoFromIcaos:","role":"symbol","title":"requestAirportsInfoFromIcaos(_:)","symbolKind":"method","modules":[{"name":"IndoorSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestAirportsInfoFromIcaos"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"requestAirportsInfoFromIcaos:","kind":"identifier"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"abstract":[{"text":"Request all info about airports","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)"],"title":"Main","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestAirportsInfoFromIcaos","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"icaosArray","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"icaosArray","content":[{"inlineContent":[{"type":"text","text":"List of icaos to request"}],"type":"paragraph"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Call it as soon as you know that the user has selected an airport or flight. It is especially recommended to provide the best user experience when there are more than one airports involved.","type":"text"}]},{"inlineContent":[{"text":"You could use this method in order to manage the cache of airports in the device`s DB.","type":"text"}],"type":"paragraph"},{"text":"Every time you call this method with a list of Icaos, two things happen:","type":"heading","anchor":"Every-time-you-call-this-method-with-a-list-of-Icaos-two-things-happen","level":2},{"inlineContent":[{"type":"text","text":"1.- The SDK try to do all requests needed to catch (or update) all airports in the icao’s list."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"2.- All airports that are in the device’s DB that are not in the list will be deleted from the DB."}]},{"content":[{"inlineContent":[{"type":"text","text":"If you call this method with an empty list, all airports in DB will be deleted."}],"type":"paragraph"}],"type":"aside","style":"warning","name":"Warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)"]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/start(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"start:","kind":"identifier"}],"abstract":[{"text":"It start all stuff","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","title":"start(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/start(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/shared":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IndoorModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[{"text":"The shared instance of IndoorSDK class.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","title":"shared","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/shared","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportsInfoFromIcaos(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestAirportsInfoFromIcaos","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}],"abstract":[{"text":"Request all info about airports","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)","title":"requestAirportsInfoFromIcaos(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requestAirportsInfoFromIcaos:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)"],"title":"Main","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"icaosArray","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"start:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/fragments"},{"op":"replace","value":"shared","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/title","op":"replace","value":"requestAirportsInfoFromIcaos:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestAirportsInfoFromIcaos:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}]}]}]}