{"metadata":{"externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)setFlight:error:","modules":[{"name":"IndoorSDK"}],"title":"setFlight(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFlight","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"setFlight:error:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/setflight(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/indoormodule\/setflight(_:)"]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Utils","anchor":"Utils","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"generated":true}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFlight","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"infoDict"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"Call with a valid dictionary and create or update the flight ticket.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Call with ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to delete the ticket.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"CreateFlightError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"As soon as requiered key is not present in the dictionary,","type":"text"},{"type":"text","text":" "},{"text":"you can know the key in the ","type":"text"},{"code":"localizedDescription","type":"codeVoice"},{"text":" property.","type":"text"}]}],"type":"aside"}]}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/PositionKey":{"url":"\/documentation\/indoorsdk\/indoormodule\/positionkey","kind":"symbol","title":"IndoorModule.PositionKey","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/PositionKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositionKey"}],"navigatorTitle":[{"text":"PositionKey","kind":"identifier"}],"abstract":[{"text":"Define the constanst keys of the position dictionary.","type":"text"}],"role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/airportIsCached(_:)":{"url":"\/documentation\/indoorsdk\/indoormodule\/airportiscached(_:)","navigatorTitle":[{"kind":"identifier","text":"airportIsCached:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"airportIsCached","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"To ask if an airport is ready"}],"title":"airportIsCached(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlight(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlight"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Manage the flight ticket in the SDK.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflight(_:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlight(_:)","title":"setFlight(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFlight:error:"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadSaveParking(inAirport:inNavController:action:)":{"title":"loadSaveParking(inAirport:inNavController:action:)","role":"symbol","abstract":[{"type":"text","text":"Open the save carpark screen inside the provide navigation controller."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)","url":"\/documentation\/indoorsdk\/indoormodule\/loadsaveparking(inairport:innavcontroller:action:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadSaveParking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAirport"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ((["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/loadCategory(_:inAirport:inNavController:action:)":{"abstract":[{"text":"It present the list of POIS in the requested category of an airport, inside the provide navigation controller.","type":"text"}],"url":"\/documentation\/indoorsdk\/indoormodule\/loadcategory(_:inairport:innavcontroller:action:)","navigatorTitle":[{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","title":"loadCategory(_:inAirport:inNavController:action:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadCategory"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"inAirport","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"inNavController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"text":": (([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getUserPosition()":{"type":"topic","navigatorTitle":[{"text":"getUserPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"User last position"}],"kind":"symbol","title":"getUserPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getuserposition()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserPosition"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setFlight:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setFlight:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getUserPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadCategory(_:inAirport:inNavController:action:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/airportIsCached(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/loadSaveParking(inAirport:inNavController:action:)"],"generated":true,"title":"Utils","anchor":"Utils"}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"setFlight:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"infoDict"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"op":"add","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"code":"YES","type":"codeVoice"},{"type":"text","text":" if the method succeeded, otherwise "},{"code":"NO","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"},"op":"add"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/title","value":"airportIsCached:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"airportIsCached:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1airportIsCached(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","value":[{"kind":"identifier","text":"IndoorModule"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/title","value":"setFlight:error:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setFlight:error:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlight(_:)\/fragments"},{"op":"replace","value":"loadSaveParkingInAirport:inNavController:error:action:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadSaveParking(inAirport:inNavController:action:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadSaveParkingInAirport:inNavController:error:action:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/title","value":"loadCategory:inAirport:inNavController:error:action:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1loadCategory(_:inAirport:inNavController:action:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadCategory:inAirport:inNavController:error:action:"}],"op":"replace"},{"op":"replace","value":"getUserPosition","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getUserPosition()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getUserPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}