{"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"generated":true,"anchor":"Deprecated","title":"Deprecated"}],"abstract":[{"text":"Set the info about the flight.","type":"text"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlightInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"flightDict","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The dictionary with all info about flight","type":"text"}]}],"name":"flightDict"}],"kind":"parameters"},{"content":[{"text":"Important","level":2,"anchor":"Important","type":"heading"},{"inlineContent":[{"type":"text","text":"If it’s not set, the button to show the flight info is hidden."}],"type":"paragraph"},{"anchor":"Deprecated","type":"heading","text":"Deprecated:","level":2},{"inlineContent":[{"type":"text","text":"Use instead of:"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":[" setFlight(_ infoDict: )"]}],"kind":"content"}],"metadata":{"modules":[{"name":"IndoorSDK"}],"role":"symbol","platforms":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFlightInfo","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)setFlightInfo:","navigatorTitle":[{"text":"setFlightInfo:","kind":"identifier"}],"title":"setFlightInfo(_:)","symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getPosition()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPosition"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"title":"getPosition()","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"User last position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","url":"\/documentation\/indoorsdk\/indoormodule\/getposition()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setPMR(_:)":{"type":"topic","abstract":[{"type":"text","text":"Switch On\/Off the "},{"type":"strong","inlineContent":[{"text":"PRM","type":"text"}]},{"type":"text","text":" routes"},{"type":"text","text":" "},{"type":"text","text":"(People Reduced Mobility)"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","role":"symbol","title":"setPMR(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPMR:"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/action":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"title":"action","kind":"symbol","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Action to be excecute when the "},{"type":"codeVoice","code":"flight info"},{"text":" ","type":"text"},{"type":"text","text":"button is pressed."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","url":"\/documentation\/indoorsdk\/indoormodule\/action"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlightInfo(_:)":{"type":"topic","abstract":[{"type":"text","text":"Set the info about the flight."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","role":"symbol","title":"setFlightInfo(_:)","kind":"symbol","navigatorTitle":[{"text":"setFlightInfo:","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFlightInfo"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"deprecated":true},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"navigatorTitle":[{"text":"IndoorModule","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndoorModule","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/indoormodule","kind":"symbol","type":"topic","title":"IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setFlightInfo:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setFlightInfo:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)"],"title":"Deprecated","generated":true,"anchor":"Deprecated"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setFlightInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"flightDict","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"parameters":[{"name":"flightDict","content":[{"inlineContent":[{"text":"The dictionary with all info about flight","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/title","value":"getPosition"},{"value":[{"text":"- ","kind":"text"},{"text":"getPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/fragments","op":"replace"},{"value":"setPMR:","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setPMR:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/fragments"},{"value":"action","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/title"},{"value":[{"text":"action","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/fragments"},{"value":"setFlightInfo:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setFlightInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","op":"replace","value":"IndoorModule"},{"value":[{"kind":"identifier","text":"IndoorModule"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IndoorModule"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/navigatorTitle","op":"replace"}]}]}