{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"on","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"true to use PMR routes,"},{"type":"text","text":" "},{"type":"text","text":"false to use normal routes."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"False is the default behaviour."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Switch On\/Off the "},{"type":"strong","inlineContent":[{"type":"text","text":"PRM"}]},{"type":"text","text":" routes"},{"type":"text","text":" "},{"type":"text","text":"(People Reduced Mobility)"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setPMR:"}],"role":"symbol","title":"setPMR(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)setPMR:","modules":[{"name":"IndoorSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"seeAlsoSections":[{"title":"Deprecated","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)"],"generated":true}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/action":{"deprecated":true,"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Action to be excecute when the "},{"type":"codeVoice","code":"flight info"},{"type":"text","text":" "},{"type":"text","text":"button is pressed."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"url":"\/documentation\/indoorsdk\/indoormodule\/action"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/getPosition()":{"deprecated":true,"role":"symbol","title":"getPosition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPosition"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"User last position"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPosition"}],"url":"\/documentation\/indoorsdk\/indoormodule\/getposition()"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"role":"symbol","title":"IndoorModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndoorModule"}],"abstract":[{"type":"text","text":"Main model class of IndoorSDK"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}],"url":"\/documentation\/indoorsdk\/indoormodule"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setPMR(_:)":{"deprecated":true,"role":"symbol","title":"setPMR(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPMR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Switch On\/Off the "},{"type":"strong","inlineContent":[{"type":"text","text":"PRM"}]},{"type":"text","text":" routes"},{"type":"text","text":" "},{"type":"text","text":"(People Reduced Mobility)"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setPMR(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPMR:"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setpmr(_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/setFlightInfo(_:)":{"deprecated":true,"role":"symbol","title":"setFlightInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFlightInfo"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Set the info about the flight."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFlightInfo:"}],"url":"\/documentation\/indoorsdk\/indoormodule\/setflightinfo(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setPMR:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPMR:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Deprecated","identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/action","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/getPosition()","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/setFlightInfo(_:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPMR:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"on"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1action\/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/title","value":"getPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1getPosition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/title","value":"setPMR:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setPMR(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPMR:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/title","value":"setFlightInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1setFlightInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFlightInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}