{"sections":[],"abstract":[{"text":"The shared instance of IndoorSDK class.","type":"text"}],"metadata":{"symbolKind":"property","title":"shared","roleHeading":"Type Property","navigatorTitle":[{"text":"shared","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndoorModule","preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule"}],"role":"symbol","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(cpy)shared","modules":[{"name":"IndoorSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","text":"IndoorModule","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"],"generated":true,"title":"Main"}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportsInfoFromIcaos(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestAirportsInfoFromIcaos","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}],"abstract":[{"text":"Request all info about airports","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)","title":"requestAirportsInfoFromIcaos(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/shared":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IndoorModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[{"text":"The shared instance of IndoorSDK class.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","title":"shared","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/shared","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/start(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"start:","kind":"identifier"}],"abstract":[{"text":"It start all stuff","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","title":"start(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/start(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"shared"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"],"title":"Main"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","text":"IndoorModule","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/title","value":"requestAirportsInfoFromIcaos:"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","value":"IndoorModule","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"kind":"identifier","text":"IndoorModule"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/title","value":"start:"},{"value":[{"kind":"text","text":"- "},{"text":"start:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/fragments"}]}]}