{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"IndoorSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"start:"}],"role":"symbol","externalID":"c:@M@IndoorSDK@objc(cs)IndoorModule(im)start:","symbolKind":"method","title":"start(_:)"},"abstract":[{"type":"text","text":"It start all stuff"}],"variants":[{"paths":["\/documentation\/indoorsdk\/indoormodule\/start(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/indoormodule\/start(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"requestLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"requestLocation","content":[{"inlineContent":[{"text":"Use to delay the request location authoritation","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Call it as soon as posible."},{"text":" ","type":"text"},{"type":"text","text":"Recomended place: AppDelegate"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["   func application(_ application: UIApplication,","    didFinishLaunchingWithOptions launchOptions:","     [UIApplication.LaunchOptionsKey: Any]?) -> Bool"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If requestLocation is false, the request location prompt will be launched when enter"},{"type":"text","text":" "},{"text":"in map.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule"]]},"kind":"symbol","seeAlsoSections":[{"title":"Main","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/shared":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IndoorModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IndoorSDK@objc(cs)IndoorModule"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[{"text":"The shared instance of IndoorSDK class.","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","title":"shared","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/shared","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/start(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"start:","kind":"identifier"}],"abstract":[{"text":"It start all stuff","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/start(_:)","title":"start(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/start(_:)","type":"topic"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule":{"abstract":[{"text":"Main model class of IndoorSDK","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule","type":"topic","title":"IndoorModule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IndoorModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/indoorsdk\/indoormodule","navigatorTitle":[{"kind":"identifier","text":"IndoorModule"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/IndoorModule/requestAirportsInfoFromIcaos(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestAirportsInfoFromIcaos","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}],"abstract":[{"text":"Request all info about airports","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)","title":"requestAirportsInfoFromIcaos(_:)","kind":"symbol","url":"\/documentation\/indoorsdk\/indoormodule\/requestairportsinfofromicaos(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"start:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"title":"Main","generated":true,"identifiers":["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/shared","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/IndoorModule\/requestAirportsInfoFromIcaos(_:)"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"start:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"requestLocation"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"value":"start:","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"start:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1start(_:)\/fragments"},{"value":"IndoorModule","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule\/fragments","value":[{"text":"IndoorModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/title","op":"replace","value":"requestAirportsInfoFromIcaos:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestAirportsInfoFromIcaos:"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1IndoorModule~1requestAirportsInfoFromIcaos(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}