{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/Equatable-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"IndoorSDK","relatedModules":["Swift"]}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@IndoorSDK@E@CreateFlightError","extendedModule":"Swift","role":"symbol","title":"!=(_:_:)","symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Operator"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/!=(_:_:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/createflighterror\/!=(_:_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/!=(_:_:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/!=(_:_:)","url":"\/documentation\/indoorsdk\/createflighterror\/!=(_:_:)"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/Equatable-Implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/indoorsdk\/createflighterror\/equatable-implementations"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","abstract":[{"text":"Errors creating a Flight, from a dict.","type":"text"}],"title":"CreateFlightError"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CreateFlightError","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title"},{"value":[{"kind":"identifier","text":"CreateFlightError"}],"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments"},{"op":"replace","value":[{"text":"CreateFlightError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}