{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"airportDestiny","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportDestiny"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/airportdestiny"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/createflighterror\/airportdestiny"]}],"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"CreateFlightError.airportDestiny","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"airportDestiny","kind":"identifier"}],"externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorAirportDestiny","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorAirportDestiny"}]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/airportDestiny":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportDestiny","title":"CreateFlightError.airportDestiny","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"airportDestiny"}],"url":"\/documentation\/indoorsdk\/createflighterror\/airportdestiny","navigatorTitle":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}],"abstract":[]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"title":"CreateFlightError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CreateFlightErrorAirportDestiny","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportDestiny\/title","value":"CreateFlightErrorAirportDestiny","op":"replace"},{"op":"replace","value":[{"text":"CreateFlightErrorAirportDestiny","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportDestiny\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","value":"CreateFlightError"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","value":[{"text":"CreateFlightError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}