{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"airportOrigin","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorAirportOrigin","navigatorTitle":[{"text":"CreateFlightErrorAirportOrigin","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"airportOrigin","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"IndoorSDK"}],"title":"CreateFlightError.airportOrigin","roleHeading":"Case"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/airportorigin"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/indoorsdk\/createflighterror\/airportorigin"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportOrigin"},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/airportOrigin":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"airportOrigin","kind":"identifier"}],"url":"\/documentation\/indoorsdk\/createflighterror\/airportorigin","kind":"symbol","abstract":[],"title":"CreateFlightError.airportOrigin","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/airportOrigin","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorAirportOrigin"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"title":"CreateFlightError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CreateFlightErrorAirportOrigin","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CreateFlightErrorAirportOrigin"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"CreateFlightErrorAirportOrigin","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","value":"CreateFlightErrorAirportOrigin","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportOrigin\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1airportOrigin\/fragments","op":"replace","value":[{"text":"CreateFlightErrorAirportOrigin","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","value":"CreateFlightError"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","value":[{"text":"CreateFlightError","kind":"identifier"}]}]}]}