{"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorCompanyCode","modules":[{"name":"IndoorSDK"}],"title":"CreateFlightError.companyCode","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyCode"}],"role":"symbol","navigatorTitle":[{"text":"CreateFlightErrorCompanyCode","kind":"identifier"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/companyCode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/createflighterror\/companycode"]},{"paths":["\/documentation\/indoorsdk\/createflighterror\/companycode"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"companyCode","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/companyCode":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"companyCode"}],"kind":"symbol","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/companyCode","title":"CreateFlightError.companyCode","url":"\/documentation\/indoorsdk\/createflighterror\/companycode","abstract":[],"navigatorTitle":[{"text":"CreateFlightErrorCompanyCode","kind":"identifier"}]},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","abstract":[{"text":"Errors creating a Flight, from a dict.","type":"text"}],"title":"CreateFlightError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"CreateFlightErrorCompanyCode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CreateFlightErrorCompanyCode"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CreateFlightErrorCompanyCode"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"CreateFlightErrorCompanyCode","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1companyCode\/title"},{"value":[{"text":"CreateFlightErrorCompanyCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1companyCode\/fragments","op":"replace"},{"value":"CreateFlightError","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title"},{"value":[{"text":"CreateFlightError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CreateFlightError"}]}]}]}