{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"icaoAirportDestiny","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportDestiny"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorIcaoAirportDestiny","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icaoAirportDestiny"}],"navigatorTitle":[{"text":"CreateFlightErrorIcaoAirportDestiny","kind":"identifier"}],"modules":[{"name":"IndoorSDK"}],"title":"CreateFlightError.icaoAirportDestiny","symbolKind":"case","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/indoorsdk\/createflighterror\/icaoairportdestiny"]},{"paths":["\/documentation\/indoorsdk\/createflighterror\/icaoairportdestiny"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"title":"CreateFlightError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/icaoAirportDestiny":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorIcaoAirportDestiny"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icaoAirportDestiny"}],"url":"\/documentation\/indoorsdk\/createflighterror\/icaoairportdestiny","title":"CreateFlightError.icaoAirportDestiny","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/icaoAirportDestiny"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"CreateFlightErrorIcaoAirportDestiny","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CreateFlightErrorIcaoAirportDestiny","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CreateFlightErrorIcaoAirportDestiny"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","op":"replace","value":"CreateFlightError"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","op":"replace","value":[{"text":"CreateFlightError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportDestiny\/title","value":"CreateFlightErrorIcaoAirportDestiny"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1icaoAirportDestiny\/fragments","op":"replace","value":[{"text":"CreateFlightErrorIcaoAirportDestiny","kind":"identifier"}]}]}]}