{"metadata":{"role":"symbol","symbolKind":"init","externalID":"s:9IndoorSDK17CreateFlightErrorO8rawValueACSgSi_tcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","modules":[{"name":"IndoorSDK"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/indoorsdk\/createflighterror\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/init(rawValue:)","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","abstract":[{"text":"Errors creating a Flight, from a dict.","type":"text"}],"title":"CreateFlightError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CreateFlightError","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","op":"replace","value":[{"text":"CreateFlightError","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CreateFlightError"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/navigatorTitle","op":"replace"}]}]}