{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nameAirportDestiny","kind":"identifier"}],"externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorNameAirportDestiny","title":"CreateFlightError.nameAirportDestiny","roleHeading":"Case","modules":[{"name":"IndoorSDK"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"CreateFlightErrorNameAirportDestiny","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportDestiny"},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameAirportDestiny"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/nameairportdestiny"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/createflighterror\/nameairportdestiny"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/nameAirportDestiny":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorNameAirportDestiny"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nameAirportDestiny","kind":"identifier"}],"title":"CreateFlightError.nameAirportDestiny","url":"\/documentation\/indoorsdk\/createflighterror\/nameairportdestiny","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/nameAirportDestiny"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"title":"CreateFlightError","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","role":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"type":"topic","abstract":[{"text":"Indoor Maping and navigation","type":"text"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","role":"collection","kind":"symbol","url":"\/documentation\/indoorsdk","title":"IndoorSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CreateFlightErrorNameAirportDestiny","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"CreateFlightErrorNameAirportDestiny"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"CreateFlightErrorNameAirportDestiny","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportDestiny\/title","value":"CreateFlightErrorNameAirportDestiny"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1nameAirportDestiny\/fragments","value":[{"text":"CreateFlightErrorNameAirportDestiny","kind":"identifier"}]},{"op":"replace","value":"CreateFlightError","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","value":[{"text":"CreateFlightError","kind":"identifier"}]}]}]}