{"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/numberflight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/createflighterror\/numberflight"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","modules":[{"name":"IndoorSDK"}],"title":"CreateFlightError.numberFlight","externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorNumberFlight","navigatorTitle":[{"text":"CreateFlightErrorNumberFlight","kind":"identifier"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"numberFlight","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/numberFlight"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"numberFlight","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateFlightError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk\/createflighterror","identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","abstract":[{"text":"Errors creating a Flight, from a dict.","type":"text"}],"title":"CreateFlightError"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","title":"IndoorSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"url":"\/documentation\/indoorsdk","kind":"symbol"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/numberFlight":{"url":"\/documentation\/indoorsdk\/createflighterror\/numberflight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"numberFlight","kind":"identifier"}],"title":"CreateFlightError.numberFlight","abstract":[],"role":"symbol","navigatorTitle":[{"text":"CreateFlightErrorNumberFlight","kind":"identifier"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/numberFlight","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CreateFlightErrorNumberFlight","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"CreateFlightErrorNumberFlight"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"CreateFlightErrorNumberFlight","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","op":"replace","value":"CreateFlightError"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","value":[{"kind":"identifier","text":"CreateFlightError"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CreateFlightError"}],"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/navigatorTitle","op":"replace"},{"value":"CreateFlightErrorNumberFlight","op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1numberFlight\/title"},{"path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1numberFlight\/fragments","value":[{"text":"CreateFlightErrorNumberFlight","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}