{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/indoorsdk\/createflighterror\/state"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/indoorsdk\/createflighterror\/state"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/state","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"}],"title":"CreateFlightError.state","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@IndoorSDK@E@CreateFlightError@CreateFlightErrorState","modules":[{"name":"IndoorSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorState"}]},"hierarchy":{"paths":[["doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError"]]},"references":{"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError":{"role":"symbol","title":"CreateFlightError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateFlightError"}],"abstract":[{"type":"text","text":"Errors creating a Flight, from a dict."}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateFlightError"}],"url":"\/documentation\/indoorsdk\/createflighterror"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK/CreateFlightError/state":{"role":"symbol","title":"CreateFlightError.state","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"}],"abstract":[],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK\/CreateFlightError\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateFlightErrorState"}],"url":"\/documentation\/indoorsdk\/createflighterror\/state"},"doc://com.geographica.IndoorSDK/documentation/IndoorSDK":{"role":"collection","title":"IndoorSDK","abstract":[{"type":"text","text":"Indoor Maping and navigation"}],"identifier":"doc:\/\/com.geographica.IndoorSDK\/documentation\/IndoorSDK","kind":"symbol","type":"topic","url":"\/documentation\/indoorsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CreateFlightErrorState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CreateFlightErrorState"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CreateFlightErrorState"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/title","value":"CreateFlightError"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError\/fragments","value":[{"kind":"identifier","text":"CreateFlightError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1state\/title","value":"CreateFlightErrorState"},{"op":"replace","path":"\/references\/doc:~1~1com.geographica.IndoorSDK~1documentation~1IndoorSDK~1CreateFlightError~1state\/fragments","value":[{"kind":"identifier","text":"CreateFlightErrorState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}